// Generated by scripts/gen-figure-images.mjs from the images in
// src/assets/figures. Do not edit by hand: add, rename, or remove an image
// there, and `npm run dev` or `npm run build` rebuilds this file.

import beginningChemistry_1_1_1 from "../assets/figures/beginning-chemistry/1.1.1.webp";
import beginningChemistry_1_2_1 from "../assets/figures/beginning-chemistry/1.2.1.webp";
import beginningChemistry_1_2_2_chemical_properties from "../assets/figures/beginning-chemistry/1.2.2-chemical-properties.webp";
import beginningChemistry_1_2_2_physical_changes from "../assets/figures/beginning-chemistry/1.2.2-physical-changes.webp";
import beginningChemistry_1_2_3 from "../assets/figures/beginning-chemistry/1.2.3.webp";
import beginningChemistry_1_2_4 from "../assets/figures/beginning-chemistry/1.2.4.webp";
import beginningChemistry_1_2_5 from "../assets/figures/beginning-chemistry/1.2.5.webp";
import beginningChemistry_1_2_6 from "../assets/figures/beginning-chemistry/1.2.6.webp";
import beginningChemistry_1_3_1 from "../assets/figures/beginning-chemistry/1.3.1.webp";
import beginningChemistry_1_3_2 from "../assets/figures/beginning-chemistry/1.3.2.webp";
import beginningChemistry_1_3_3 from "../assets/figures/beginning-chemistry/1.3.3.webp";
import beginningChemistry_2_1_1 from "../assets/figures/beginning-chemistry/2.1.1.webp";
import beginningChemistry_2_2_1 from "../assets/figures/beginning-chemistry/2.2.1.webp";
import beginningChemistry_2_2_2 from "../assets/figures/beginning-chemistry/2.2.2.webp";
import beginningChemistry_2_3_1 from "../assets/figures/beginning-chemistry/2.3.1.webp";
import beginningChemistry_2_3_2 from "../assets/figures/beginning-chemistry/2.3.2.webp";
import beginningChemistry_2_3_3 from "../assets/figures/beginning-chemistry/2.3.3.webp";
import beginningChemistry_2_4_image_1 from "../assets/figures/beginning-chemistry/2.4-image-1.webp";
import beginningChemistry_2_4_image_2 from "../assets/figures/beginning-chemistry/2.4-image-2.webp";
import beginningChemistry_2_4_image_3 from "../assets/figures/beginning-chemistry/2.4-image-3.webp";
import beginningChemistry_2_4_image_4 from "../assets/figures/beginning-chemistry/2.4-image-4.webp";
import beginningChemistry_2_4_image_5 from "../assets/figures/beginning-chemistry/2.4-image-5.webp";
import beginningChemistry_2_4_1 from "../assets/figures/beginning-chemistry/2.4.1.webp";
import beginningChemistry_2_4_2 from "../assets/figures/beginning-chemistry/2.4.2.webp";
import beginningChemistry_3_1_image_1 from "../assets/figures/beginning-chemistry/3.1-image-1.webp";
import beginningChemistry_3_2_1_a_simple_periodic_table from "../assets/figures/beginning-chemistry/3.2.1-a-simple-periodic-table.webp";
import beginningChemistry_3_2_1_the_structure_of_the_atom from "../assets/figures/beginning-chemistry/3.2.1-the-structure-of-the-atom.webp";
import beginningChemistry_3_3_1 from "../assets/figures/beginning-chemistry/3.3.1.webp";
import beginningChemistry_3_4_2 from "../assets/figures/beginning-chemistry/3.4.2.webp";
import beginningChemistry_3_5_1 from "../assets/figures/beginning-chemistry/3.5.1.webp";
import beginningChemistry_3_5_2 from "../assets/figures/beginning-chemistry/3.5.2.webp";
import beginningChemistry_4_1_1 from "../assets/figures/beginning-chemistry/4.1.1.webp";
import beginningChemistry_4_3_1 from "../assets/figures/beginning-chemistry/4.3.1.webp";
import beginningChemistry_4_3_2 from "../assets/figures/beginning-chemistry/4.3.2.webp";
import beginningChemistry_4_4_1 from "../assets/figures/beginning-chemistry/4.4.1.webp";
import beginningChemistry_4_4_2 from "../assets/figures/beginning-chemistry/4.4.2.webp";
import beginningChemistry_4_4_3 from "../assets/figures/beginning-chemistry/4.4.3.webp";
import beginningChemistry_4_7_1 from "../assets/figures/beginning-chemistry/4.7.1.webp";
import beginningChemistry_5_1_1 from "../assets/figures/beginning-chemistry/5.1.1.webp";
import beginningChemistry_5_7_2 from "../assets/figures/beginning-chemistry/5.7.2.webp";
import beginningChemistry_6_1_image_1 from "../assets/figures/beginning-chemistry/6.1-image-1.webp";
import beginningChemistry_6_2_1 from "../assets/figures/beginning-chemistry/6.2.1.webp";
import beginningChemistry_6_4_1 from "../assets/figures/beginning-chemistry/6.4.1.webp";
import beginningChemistry_6_4_2 from "../assets/figures/beginning-chemistry/6.4.2.webp";
import beginningChemistry_6_6_1 from "../assets/figures/beginning-chemistry/6.6.1.webp";
import beginningChemistry_6_6_2 from "../assets/figures/beginning-chemistry/6.6.2.webp";
import beginningChemistry_6_7_1 from "../assets/figures/beginning-chemistry/6.7.1.webp";
import beginningChemistry_7_3_1 from "../assets/figures/beginning-chemistry/7.3.1.webp";
import beginningChemistry_7_4_1 from "../assets/figures/beginning-chemistry/7.4.1.webp";
import beginningChemistry_7_4_2 from "../assets/figures/beginning-chemistry/7.4.2.webp";
import beginningChemistry_7_5_1 from "../assets/figures/beginning-chemistry/7.5.1.webp";
import beginningChemistry_8_1_1 from "../assets/figures/beginning-chemistry/8.1.1.webp";
import beginningChemistry_8_2_1 from "../assets/figures/beginning-chemistry/8.2.1.webp";
import beginningChemistry_8_2_2 from "../assets/figures/beginning-chemistry/8.2.2.webp";
import beginningChemistry_8_3_1 from "../assets/figures/beginning-chemistry/8.3.1.webp";
import beginningChemistry_8_3_2 from "../assets/figures/beginning-chemistry/8.3.2.webp";
import beginningChemistry_8_3_3 from "../assets/figures/beginning-chemistry/8.3.3.webp";
import beginningChemistry_8_3_4 from "../assets/figures/beginning-chemistry/8.3.4.webp";
import beginningChemistry_8_4_1 from "../assets/figures/beginning-chemistry/8.4.1.webp";
import beginningChemistry_8_5_1 from "../assets/figures/beginning-chemistry/8.5.1.webp";
import beginningChemistry_8_5_2 from "../assets/figures/beginning-chemistry/8.5.2.webp";
import beginningChemistry_8_5_3 from "../assets/figures/beginning-chemistry/8.5.3.webp";
import beginningChemistry_8_5_4 from "../assets/figures/beginning-chemistry/8.5.4.webp";
import beginningChemistry_8_5_5 from "../assets/figures/beginning-chemistry/8.5.5.webp";
import beginningChemistry_8_5_6 from "../assets/figures/beginning-chemistry/8.5.6.webp";
import beginningChemistry_8_5_7 from "../assets/figures/beginning-chemistry/8.5.7.webp";
import beginningChemistry_8_5_8 from "../assets/figures/beginning-chemistry/8.5.8.webp";
import beginningChemistry_8_5_9 from "../assets/figures/beginning-chemistry/8.5.9.webp";
import beginningChemistry_8_5_10 from "../assets/figures/beginning-chemistry/8.5.10.webp";
import beginningChemistry_8_6_1 from "../assets/figures/beginning-chemistry/8.6.1.webp";
import beginningChemistry_8_6_2 from "../assets/figures/beginning-chemistry/8.6.2.webp";
import beginningChemistry_8_6_3 from "../assets/figures/beginning-chemistry/8.6.3.webp";
import beginningChemistry_9_4_image_3 from "../assets/figures/beginning-chemistry/9.4-image-3.webp";
import beginningChemistry_9_4_image_6 from "../assets/figures/beginning-chemistry/9.4-image-6.webp";
import beginningChemistry_9_4_image_7 from "../assets/figures/beginning-chemistry/9.4-image-7.webp";
import beginningChemistry_9_4_image_8 from "../assets/figures/beginning-chemistry/9.4-image-8.webp";
import beginningChemistry_9_4_image_9 from "../assets/figures/beginning-chemistry/9.4-image-9.webp";
import beginningChemistry_9_4_image_10 from "../assets/figures/beginning-chemistry/9.4-image-10.webp";
import beginningChemistry_9_4_image_11 from "../assets/figures/beginning-chemistry/9.4-image-11.webp";
import beginningChemistry_9_4_image_12 from "../assets/figures/beginning-chemistry/9.4-image-12.webp";
import beginningChemistry_9_4_image_13 from "../assets/figures/beginning-chemistry/9.4-image-13.webp";
import beginningChemistry_9_4_image_14 from "../assets/figures/beginning-chemistry/9.4-image-14.webp";
import beginningChemistry_9_4_image_15 from "../assets/figures/beginning-chemistry/9.4-image-15.webp";
import beginningChemistry_9_4_image_16 from "../assets/figures/beginning-chemistry/9.4-image-16.webp";
import beginningChemistry_9_4_image_17 from "../assets/figures/beginning-chemistry/9.4-image-17.webp";
import beginningChemistry_9_4_image_18 from "../assets/figures/beginning-chemistry/9.4-image-18.webp";
import beginningChemistry_9_4_image_19 from "../assets/figures/beginning-chemistry/9.4-image-19.webp";
import beginningChemistry_9_4_image_20 from "../assets/figures/beginning-chemistry/9.4-image-20.webp";
import beginningChemistry_9_4_image_21 from "../assets/figures/beginning-chemistry/9.4-image-21.webp";
import beginningChemistry_9_4_image_22 from "../assets/figures/beginning-chemistry/9.4-image-22.webp";
import beginningChemistry_9_4_image_23 from "../assets/figures/beginning-chemistry/9.4-image-23.webp";
import beginningChemistry_9_4_image_24 from "../assets/figures/beginning-chemistry/9.4-image-24.webp";
import beginningChemistry_9_4_image_25 from "../assets/figures/beginning-chemistry/9.4-image-25.webp";
import beginningChemistry_9_4_image_26 from "../assets/figures/beginning-chemistry/9.4-image-26.webp";
import beginningChemistry_9_4_image_27 from "../assets/figures/beginning-chemistry/9.4-image-27.webp";
import beginningChemistry_9_5_image_2 from "../assets/figures/beginning-chemistry/9.5-image-2.webp";
import beginningChemistry_9_5_image_4 from "../assets/figures/beginning-chemistry/9.5-image-4.webp";
import beginningChemistry_9_5_image_5 from "../assets/figures/beginning-chemistry/9.5-image-5.webp";
import beginningChemistry_9_6_image_2 from "../assets/figures/beginning-chemistry/9.6-image-2.webp";
import beginningChemistry_9_6_image_3 from "../assets/figures/beginning-chemistry/9.6-image-3.webp";
import beginningChemistry_9_6_image_4 from "../assets/figures/beginning-chemistry/9.6-image-4.webp";
import beginningChemistry_9_6_image_5 from "../assets/figures/beginning-chemistry/9.6-image-5.webp";
import beginningChemistry_9_6_image_6 from "../assets/figures/beginning-chemistry/9.6-image-6.webp";
import beginningChemistry_9_7_image_2 from "../assets/figures/beginning-chemistry/9.7-image-2.webp";
import beginningChemistry_9_7_image_3 from "../assets/figures/beginning-chemistry/9.7-image-3.webp";
import beginningChemistry_9_7_image_4 from "../assets/figures/beginning-chemistry/9.7-image-4.webp";
import beginningChemistry_9_7_image_5 from "../assets/figures/beginning-chemistry/9.7-image-5.webp";
import beginningChemistry_9_7_image_6 from "../assets/figures/beginning-chemistry/9.7-image-6.webp";
import beginningChemistry_9_7_image_7 from "../assets/figures/beginning-chemistry/9.7-image-7.webp";
import beginningChemistry_9_7_image_8 from "../assets/figures/beginning-chemistry/9.7-image-8.webp";
import beginningChemistry_9_7_image_9 from "../assets/figures/beginning-chemistry/9.7-image-9.webp";
import beginningChemistry_9_7_image_10 from "../assets/figures/beginning-chemistry/9.7-image-10.webp";
import type { BookKey, FigureImage } from "./types";

export const FIGURE_IMAGES: Partial<Record<BookKey, Record<string, FigureImage>>> = {
  "beginning-chemistry": {
    "1.1.1": { src: beginningChemistry_1_1_1, width: 1448, height: 1086 },
    "1.2.1": { src: beginningChemistry_1_2_1, width: 1600, height: 533 },
    "1.2.2-chemical-properties": { src: beginningChemistry_1_2_2_chemical_properties, width: 1536, height: 1024 },
    "1.2.2-physical-changes": { src: beginningChemistry_1_2_2_physical_changes, width: 1448, height: 1086 },
    "1.2.3": { src: beginningChemistry_1_2_3, width: 1448, height: 1086 },
    "1.2.4": { src: beginningChemistry_1_2_4, width: 1600, height: 800 },
    "1.2.5": { src: beginningChemistry_1_2_5, width: 1536, height: 1024 },
    "1.2.6": { src: beginningChemistry_1_2_6, width: 1448, height: 1086 },
    "1.3.1": { src: beginningChemistry_1_3_1, width: 1448, height: 1086 },
    "1.3.2": { src: beginningChemistry_1_3_2, width: 1536, height: 1024 },
    "1.3.3": { src: beginningChemistry_1_3_3, width: 1448, height: 1086 },
    "2.1.1": { src: beginningChemistry_2_1_1, width: 1536, height: 1024 },
    "2.2.1": { src: beginningChemistry_2_2_1, width: 1266, height: 1243 },
    "2.2.2": { src: beginningChemistry_2_2_2, width: 1448, height: 1086 },
    "2.3.1": { src: beginningChemistry_2_3_1, width: 1448, height: 1086 },
    "2.3.2": { src: beginningChemistry_2_3_2, width: 1536, height: 1024 },
    "2.3.3": { src: beginningChemistry_2_3_3, width: 1448, height: 1086 },
    "2.4-image-1": { src: beginningChemistry_2_4_image_1, width: 1536, height: 1024 },
    "2.4-image-2": { src: beginningChemistry_2_4_image_2, width: 1536, height: 512 },
    "2.4-image-3": { src: beginningChemistry_2_4_image_3, width: 1536, height: 512 },
    "2.4-image-4": { src: beginningChemistry_2_4_image_4, width: 1536, height: 576 },
    "2.4-image-5": { src: beginningChemistry_2_4_image_5, width: 1536, height: 576 },
    "2.4.1": { src: beginningChemistry_2_4_1, width: 1536, height: 1024 },
    "2.4.2": { src: beginningChemistry_2_4_2, width: 1774, height: 887 },
    "3.1-image-1": { src: beginningChemistry_3_1_image_1, width: 1158, height: 663 },
    "3.2.1-a-simple-periodic-table": { src: beginningChemistry_3_2_1_a_simple_periodic_table, width: 1536, height: 1024 },
    "3.2.1-the-structure-of-the-atom": { src: beginningChemistry_3_2_1_the_structure_of_the_atom, width: 1448, height: 1086 },
    "3.3.1": { src: beginningChemistry_3_3_1, width: 1448, height: 1086 },
    "3.4.2": { src: beginningChemistry_3_4_2, width: 1774, height: 887 },
    "3.5.1": { src: beginningChemistry_3_5_1, width: 1448, height: 1086 },
    "3.5.2": { src: beginningChemistry_3_5_2, width: 1122, height: 1402 },
    "4.1.1": { src: beginningChemistry_4_1_1, width: 1448, height: 1086 },
    "4.3.1": { src: beginningChemistry_4_3_1, width: 1536, height: 1024 },
    "4.3.2": { src: beginningChemistry_4_3_2, width: 1122, height: 1402 },
    "4.4.1": { src: beginningChemistry_4_4_1, width: 1448, height: 1086 },
    "4.4.2": { src: beginningChemistry_4_4_2, width: 1293, height: 1217 },
    "4.4.3": { src: beginningChemistry_4_4_3, width: 1448, height: 1086 },
    "4.7.1": { src: beginningChemistry_4_7_1, width: 1536, height: 1024 },
    "5.1.1": { src: beginningChemistry_5_1_1, width: 1536, height: 1024 },
    "5.7.2": { src: beginningChemistry_5_7_2, width: 1448, height: 1086 },
    "6.1-image-1": { src: beginningChemistry_6_1_image_1, width: 1448, height: 1086 },
    "6.2.1": { src: beginningChemistry_6_2_1, width: 1448, height: 1086 },
    "6.4.1": { src: beginningChemistry_6_4_1, width: 1448, height: 1086 },
    "6.4.2": { src: beginningChemistry_6_4_2, width: 1448, height: 1086 },
    "6.6.1": { src: beginningChemistry_6_6_1, width: 1448, height: 1086 },
    "6.6.2": { src: beginningChemistry_6_6_2, width: 1536, height: 1024 },
    "6.7.1": { src: beginningChemistry_6_7_1, width: 1374, height: 1145 },
    "7.3.1": { src: beginningChemistry_7_3_1, width: 1536, height: 1024 },
    "7.4.1": { src: beginningChemistry_7_4_1, width: 1448, height: 1086 },
    "7.4.2": { src: beginningChemistry_7_4_2, width: 1448, height: 1086 },
    "7.5.1": { src: beginningChemistry_7_5_1, width: 1536, height: 1024 },
    "8.1.1": { src: beginningChemistry_8_1_1, width: 1448, height: 1086 },
    "8.2.1": { src: beginningChemistry_8_2_1, width: 1448, height: 1086 },
    "8.2.2": { src: beginningChemistry_8_2_2, width: 1774, height: 887 },
    "8.3.1": { src: beginningChemistry_8_3_1, width: 1448, height: 1086 },
    "8.3.2": { src: beginningChemistry_8_3_2, width: 1448, height: 1086 },
    "8.3.3": { src: beginningChemistry_8_3_3, width: 1448, height: 1086 },
    "8.3.4": { src: beginningChemistry_8_3_4, width: 1122, height: 1402 },
    "8.4.1": { src: beginningChemistry_8_4_1, width: 1129, height: 1393 },
    "8.5.1": { src: beginningChemistry_8_5_1, width: 1448, height: 1086 },
    "8.5.2": { src: beginningChemistry_8_5_2, width: 1448, height: 1086 },
    "8.5.3": { src: beginningChemistry_8_5_3, width: 1448, height: 1086 },
    "8.5.4": { src: beginningChemistry_8_5_4, width: 1448, height: 1086 },
    "8.5.5": { src: beginningChemistry_8_5_5, width: 1448, height: 1086 },
    "8.5.6": { src: beginningChemistry_8_5_6, width: 1448, height: 1086 },
    "8.5.7": { src: beginningChemistry_8_5_7, width: 1448, height: 1086 },
    "8.5.8": { src: beginningChemistry_8_5_8, width: 1448, height: 1086 },
    "8.5.9": { src: beginningChemistry_8_5_9, width: 1448, height: 1086 },
    "8.5.10": { src: beginningChemistry_8_5_10, width: 1448, height: 1086 },
    "8.6.1": { src: beginningChemistry_8_6_1, width: 1448, height: 1086 },
    "8.6.2": { src: beginningChemistry_8_6_2, width: 1448, height: 1086 },
    "8.6.3": { src: beginningChemistry_8_6_3, width: 1448, height: 1086 },
    "9.4-image-3": { src: beginningChemistry_9_4_image_3, width: 1200, height: 188 },
    "9.4-image-6": { src: beginningChemistry_9_4_image_6, width: 1200, height: 188 },
    "9.4-image-7": { src: beginningChemistry_9_4_image_7, width: 1200, height: 188 },
    "9.4-image-8": { src: beginningChemistry_9_4_image_8, width: 1200, height: 188 },
    "9.4-image-9": { src: beginningChemistry_9_4_image_9, width: 1200, height: 188 },
    "9.4-image-10": { src: beginningChemistry_9_4_image_10, width: 1200, height: 188 },
    "9.4-image-11": { src: beginningChemistry_9_4_image_11, width: 1200, height: 188 },
    "9.4-image-12": { src: beginningChemistry_9_4_image_12, width: 1200, height: 188 },
    "9.4-image-13": { src: beginningChemistry_9_4_image_13, width: 1200, height: 264 },
    "9.4-image-14": { src: beginningChemistry_9_4_image_14, width: 1200, height: 188 },
    "9.4-image-15": { src: beginningChemistry_9_4_image_15, width: 1200, height: 264 },
    "9.4-image-16": { src: beginningChemistry_9_4_image_16, width: 1200, height: 282 },
    "9.4-image-17": { src: beginningChemistry_9_4_image_17, width: 1200, height: 336 },
    "9.4-image-18": { src: beginningChemistry_9_4_image_18, width: 1200, height: 340 },
    "9.4-image-19": { src: beginningChemistry_9_4_image_19, width: 1200, height: 424 },
    "9.4-image-20": { src: beginningChemistry_9_4_image_20, width: 1200, height: 264 },
    "9.4-image-21": { src: beginningChemistry_9_4_image_21, width: 1200, height: 264 },
    "9.4-image-22": { src: beginningChemistry_9_4_image_22, width: 1200, height: 332 },
    "9.4-image-23": { src: beginningChemistry_9_4_image_23, width: 1200, height: 280 },
    "9.4-image-24": { src: beginningChemistry_9_4_image_24, width: 1200, height: 188 },
    "9.4-image-25": { src: beginningChemistry_9_4_image_25, width: 1200, height: 188 },
    "9.4-image-26": { src: beginningChemistry_9_4_image_26, width: 1200, height: 188 },
    "9.4-image-27": { src: beginningChemistry_9_4_image_27, width: 1200, height: 336 },
    "9.5-image-2": { src: beginningChemistry_9_5_image_2, width: 1200, height: 188 },
    "9.5-image-4": { src: beginningChemistry_9_5_image_4, width: 1200, height: 258 },
    "9.5-image-5": { src: beginningChemistry_9_5_image_5, width: 1200, height: 324 },
    "9.6-image-2": { src: beginningChemistry_9_6_image_2, width: 1200, height: 362 },
    "9.6-image-3": { src: beginningChemistry_9_6_image_3, width: 1200, height: 412 },
    "9.6-image-4": { src: beginningChemistry_9_6_image_4, width: 1200, height: 188 },
    "9.6-image-5": { src: beginningChemistry_9_6_image_5, width: 1200, height: 444 },
    "9.6-image-6": { src: beginningChemistry_9_6_image_6, width: 1200, height: 188 },
    "9.7-image-2": { src: beginningChemistry_9_7_image_2, width: 1200, height: 362 },
    "9.7-image-3": { src: beginningChemistry_9_7_image_3, width: 1200, height: 246 },
    "9.7-image-4": { src: beginningChemistry_9_7_image_4, width: 1200, height: 352 },
    "9.7-image-5": { src: beginningChemistry_9_7_image_5, width: 1200, height: 262 },
    "9.7-image-6": { src: beginningChemistry_9_7_image_6, width: 1200, height: 242 },
    "9.7-image-7": { src: beginningChemistry_9_7_image_7, width: 1200, height: 264 },
    "9.7-image-8": { src: beginningChemistry_9_7_image_8, width: 1200, height: 318 },
    "9.7-image-9": { src: beginningChemistry_9_7_image_9, width: 1200, height: 272 },
    "9.7-image-10": { src: beginningChemistry_9_7_image_10, width: 1200, height: 246 },
  },
};
