// Generated by scripts/gen-learning-paths.mjs from the front matter in
// sources/openstax. Do not edit by hand; run `npm run gen:paths` instead.

export interface PathSection {
  number: string;
  title: string;
  /** False while the section is still an empty stub. */
  ready: boolean;
  /** Path under sources/openstax, for loading the text. */
  file: string;
  /** The original page, for attribution and "Read the original". */
  sourceUrl: string;
}

export interface PathChapter {
  number: number;
  title: string;
  sections: PathSection[];
}

export interface BookMeta {
  title: string;
  author: string;
  license: string;
}

export type BookKey = "beginning-chemistry" | "chemistry-1e";

export const BOOK_CHAPTERS: Record<BookKey, PathChapter[]> = {
  "beginning-chemistry": [
    {
      "number": 1,
      "title": "What Is Chemistry?",
      "sections": [
        {
          "number": "1.1",
          "title": "Prelude to Chemistry",
          "ready": true,
          "file": "introductory/What-Is-Chemistry/01-1-Prelude-to-Chemistry.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/Introductory_Chemistry/Beginning_Chemistry_(Ball)/01%3A_What_Is_Chemistry/1.01%3A_Prelude_to_Chemistry"
        },
        {
          "number": "1.2",
          "title": "Basic Definitions",
          "ready": true,
          "file": "introductory/What-Is-Chemistry/01-2-Basic-Definitions.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/Introductory_Chemistry/Beginning_Chemistry_(Ball)/01%3A_What_Is_Chemistry/1.02%3A_Basic_Definitions"
        },
        {
          "number": "1.3",
          "title": "Chemistry as a Science",
          "ready": true,
          "file": "introductory/What-Is-Chemistry/01-3-Chemistry-as-a-Science.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/Introductory_Chemistry/Beginning_Chemistry_(Ball)/01%3A_What_Is_Chemistry/1.03%3A_Chemistry_as_a_Science"
        }
      ]
    },
    {
      "number": 2,
      "title": "Measurements",
      "sections": [
        {
          "number": "2.1",
          "title": "Prelude to Measurements",
          "ready": true,
          "file": "introductory/Measurements/02-1-Prelude-to-Measurements.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/Introductory_Chemistry/Beginning_Chemistry_(Ball)/02%3A_Measurements/2.01%3A_Prelude_to_Measurements"
        },
        {
          "number": "2.2",
          "title": "Expressing Numbers",
          "ready": true,
          "file": "introductory/Measurements/02-2-Expressing-Numbers.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/Introductory_Chemistry/Beginning_Chemistry_(Ball)/02%3A_Measurements/2.02%3A_Expressing_Numbers"
        },
        {
          "number": "2.3",
          "title": "Expressing Units",
          "ready": true,
          "file": "introductory/Measurements/02-3-Expressing-Units.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/Introductory_Chemistry/Beginning_Chemistry_(Ball)/02%3A_Measurements/2.03%3A_Expressing_Units"
        },
        {
          "number": "2.4",
          "title": "Significant Figures",
          "ready": true,
          "file": "introductory/Measurements/02-4-Significant-Figures.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/Introductory_Chemistry/Beginning_Chemistry_(Ball)/02%3A_Measurements/2.04%3A_Significant_Figures"
        },
        {
          "number": "2.5",
          "title": "Converting Units",
          "ready": true,
          "file": "introductory/Measurements/02-5-Converting-Units.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/Introductory_Chemistry/Beginning_Chemistry_(Ball)/02%3A_Measurements/2.05%3A_Converting_Units"
        },
        {
          "number": "2.6",
          "title": "Other Units - Temperature and Density",
          "ready": true,
          "file": "introductory/Measurements/02-6-Other-Units-Temperature-and-Density.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/Introductory_Chemistry/Beginning_Chemistry_(Ball)/02%3A_Measurements/2.06%3A_Other_Units_-_Temperature_and_Density"
        }
      ]
    },
    {
      "number": 3,
      "title": "Atoms, Molecules, and Ions",
      "sections": [
        {
          "number": "3.1",
          "title": "Prelude to Atoms, Molecules, and Ions",
          "ready": true,
          "file": "introductory/Atoms-Molecules-and-Ions/03-1-Prelude-to-Atoms-Molecules-and-Ions.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/Introductory_Chemistry/Beginning_Chemistry_(Ball)/03%3A_Atoms_Molecules_and_Ions/3.01%3A_Prelude_to_Atoms_Molecules_and_Ions"
        },
        {
          "number": "3.2",
          "title": "Atomic Theory",
          "ready": true,
          "file": "introductory/Atoms-Molecules-and-Ions/03-2-Atomic-Theory.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/Introductory_Chemistry/Beginning_Chemistry_(Ball)/03%3A_Atoms_Molecules_and_Ions/3.02%3A_Atomic_Theory"
        },
        {
          "number": "3.3",
          "title": "Molecules and Chemical Nomenclature",
          "ready": true,
          "file": "introductory/Atoms-Molecules-and-Ions/03-3-Molecules-and-Chemical-Nomenclature.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/Introductory_Chemistry/Beginning_Chemistry_(Ball)/03%3A_Atoms_Molecules_and_Ions/3.03%3A_Molecules_and_Chemical_Nomenclature"
        },
        {
          "number": "3.4",
          "title": "Masses of Atoms and Molecules",
          "ready": true,
          "file": "introductory/Atoms-Molecules-and-Ions/03-4-Masses-of-Atoms-and-Molecules.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/Introductory_Chemistry/Beginning_Chemistry_(Ball)/03%3A_Atoms_Molecules_and_Ions/3.04%3A_Masses_of_Atoms_and_Molecules"
        },
        {
          "number": "3.5",
          "title": "Ions and Ionic Compounds",
          "ready": true,
          "file": "introductory/Atoms-Molecules-and-Ions/03-5-Ions-and-Ionic-Compounds.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/Introductory_Chemistry/Beginning_Chemistry_(Ball)/03%3A_Atoms_Molecules_and_Ions/3.05%3A_Ions_and_Ionic_Compounds"
        },
        {
          "number": "3.6",
          "title": "Acids",
          "ready": true,
          "file": "introductory/Atoms-Molecules-and-Ions/03-6-Acids.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/Introductory_Chemistry/Beginning_Chemistry_(Ball)/03%3A_Atoms_Molecules_and_Ions/3.06%3A_Acids"
        }
      ]
    },
    {
      "number": 4,
      "title": "Chemical Reactions and Equations",
      "sections": [
        {
          "number": "4.1",
          "title": "Prelude to Chemical Reactions",
          "ready": true,
          "file": "introductory/Chemical-Reactions-and-Equations/04-1-Prelude-to-Chemical-Reactions.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/Introductory_Chemistry/Beginning_Chemistry_(Ball)/04%3A_Chemical_Reactions_and_Equations/4.01%3A_Prelude_to_Chemical_Reactions"
        },
        {
          "number": "4.2",
          "title": "The Chemical Equation",
          "ready": true,
          "file": "introductory/Chemical-Reactions-and-Equations/04-2-The-Chemical-Equation.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/Introductory_Chemistry/Beginning_Chemistry_(Ball)/04%3A_Chemical_Reactions_and_Equations/4.02%3A_The_Chemical_Equation"
        },
        {
          "number": "4.3",
          "title": "Types of Chemical Reactions - Single and Double Replacement Reactions",
          "ready": true,
          "file": "introductory/Chemical-Reactions-and-Equations/04-3-Types-of-Chemical-Reactions-Single-and-Double-Replacement-Reactions.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/Introductory_Chemistry/Beginning_Chemistry_(Ball)/04%3A_Chemical_Reactions_and_Equations/4.03%3A_Types_of_Chemical_Reactions_-_Single_and_Double_Replacement_Reactions"
        },
        {
          "number": "4.4",
          "title": "Ionic Equations - A Closer Look",
          "ready": true,
          "file": "introductory/Chemical-Reactions-and-Equations/04-4-Ionic-Equations-A-Closer-Look.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/Introductory_Chemistry/Beginning_Chemistry_(Ball)/04%3A_Chemical_Reactions_and_Equations/4.04%3A_Ionic_Equations_-_A_Closer_Look"
        },
        {
          "number": "4.5",
          "title": "Composition, Decomposition, and Combustion Reactions",
          "ready": true,
          "file": "introductory/Chemical-Reactions-and-Equations/04-5-Composition-Decomposition-and-Combustion-Reactions.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/Introductory_Chemistry/Beginning_Chemistry_(Ball)/04%3A_Chemical_Reactions_and_Equations/4.05%3A_Composition_Decomposition_and_Combustion_Reactions"
        },
        {
          "number": "4.6",
          "title": "Neutralization Reactions",
          "ready": true,
          "file": "introductory/Chemical-Reactions-and-Equations/04-6-Neutralization-Reactions.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/Introductory_Chemistry/Beginning_Chemistry_(Ball)/04%3A_Chemical_Reactions_and_Equations/4.06%3A_Neutralization_Reactions"
        },
        {
          "number": "4.7",
          "title": "Oxidation-Reduction Reactions",
          "ready": true,
          "file": "introductory/Chemical-Reactions-and-Equations/04-7-Oxidation-Reduction-Reactions.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/Introductory_Chemistry/Beginning_Chemistry_(Ball)/04%3A_Chemical_Reactions_and_Equations/4.07%3A_Oxidation-Reduction_Reactions"
        }
      ]
    },
    {
      "number": 5,
      "title": "Stoichiometry and the Mole",
      "sections": [
        {
          "number": "5.1",
          "title": "Introduction",
          "ready": true,
          "file": "introductory/Stoichiometry-and-the-Mole/05-1-Introduction.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/Introductory_Chemistry/Beginning_Chemistry_(Ball)/05%3A_Stoichiometry_and_the_Mole/5.01%3A_Introduction"
        },
        {
          "number": "5.2",
          "title": "Stoichiometry",
          "ready": true,
          "file": "introductory/Stoichiometry-and-the-Mole/05-2-Stoichiometry.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/Introductory_Chemistry/Beginning_Chemistry_(Ball)/05%3A_Stoichiometry_and_the_Mole/5.02%3A_Stoichiometry"
        },
        {
          "number": "5.3",
          "title": "The Mole",
          "ready": true,
          "file": "introductory/Stoichiometry-and-the-Mole/05-3-The-Mole.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/Introductory_Chemistry/Beginning_Chemistry_(Ball)/05%3A_Stoichiometry_and_the_Mole/5.03%3A_The_Mole"
        },
        {
          "number": "5.4",
          "title": "The Mole in Chemical Reactions",
          "ready": true,
          "file": "introductory/Stoichiometry-and-the-Mole/05-4-The-Mole-in-Chemical-Reactions.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/Introductory_Chemistry/Beginning_Chemistry_(Ball)/05%3A_Stoichiometry_and_the_Mole/5.04%3A_The_Mole_in_Chemical_Reactions"
        },
        {
          "number": "5.5",
          "title": "Mole-Mass and Mass-Mass Calculations",
          "ready": true,
          "file": "introductory/Stoichiometry-and-the-Mole/05-5-Mole-Mass-and-Mass-Mass-Calculations.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/Introductory_Chemistry/Beginning_Chemistry_(Ball)/05%3A_Stoichiometry_and_the_Mole/5.05%3A_Mole-Mass_and_Mass-Mass_Calculations"
        },
        {
          "number": "5.6",
          "title": "Yields",
          "ready": true,
          "file": "introductory/Stoichiometry-and-the-Mole/05-6-Yields.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/Introductory_Chemistry/Beginning_Chemistry_(Ball)/05%3A_Stoichiometry_and_the_Mole/5.06%3A_Yields"
        },
        {
          "number": "5.7",
          "title": "Limiting Reagents",
          "ready": true,
          "file": "introductory/Stoichiometry-and-the-Mole/05-7-Limiting-Reagents.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/Introductory_Chemistry/Beginning_Chemistry_(Ball)/05%3A_Stoichiometry_and_the_Mole/5.07%3A_Limiting_Reagents"
        }
      ]
    },
    {
      "number": 6,
      "title": "Gases",
      "sections": [
        {
          "number": "6.1",
          "title": "Prelude to Gases",
          "ready": true,
          "file": "introductory/Gases/06-1-Prelude-to-Gases.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/Introductory_Chemistry/Beginning_Chemistry_(Ball)/06%3A_Gases/6.01%3A_Prelude_to_Gases"
        },
        {
          "number": "6.2",
          "title": "Kinetic Theory of Gases",
          "ready": true,
          "file": "introductory/Gases/06-2-Kinetic-Theory-of-Gases.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/Introductory_Chemistry/Beginning_Chemistry_(Ball)/06%3A_Gases/6.02%3A_Kinetic_Theory_of_Gases"
        },
        {
          "number": "6.3",
          "title": "Pressure",
          "ready": true,
          "file": "introductory/Gases/06-3-Pressure.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/Introductory_Chemistry/Beginning_Chemistry_(Ball)/06%3A_Gases/6.03%3A_Pressure"
        },
        {
          "number": "6.4",
          "title": "Gas Laws",
          "ready": true,
          "file": "introductory/Gases/06-4-Gas-Laws.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/Introductory_Chemistry/Beginning_Chemistry_(Ball)/06%3A_Gases/6.04%3A_Gas_Laws"
        },
        {
          "number": "6.5",
          "title": "Other Gas Laws",
          "ready": true,
          "file": "introductory/Gases/06-5-Other-Gas-Laws.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/Introductory_Chemistry/Beginning_Chemistry_(Ball)/06%3A_Gases/6.05%3A_Other_Gas_Laws"
        },
        {
          "number": "6.6",
          "title": "The Ideal Gas Law and Some Applications",
          "ready": true,
          "file": "introductory/Gases/06-6-The-Ideal-Gas-Law-and-Some-Applications.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/Introductory_Chemistry/Beginning_Chemistry_(Ball)/06%3A_Gases/6.06%3A_The_Ideal_Gas_Law_and_Some_Applications"
        },
        {
          "number": "6.7",
          "title": "Gas Mixtures",
          "ready": true,
          "file": "introductory/Gases/06-7-Gas-Mixtures.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/Introductory_Chemistry/Beginning_Chemistry_(Ball)/06%3A_Gases/6.07%3A_Gas_Mixtures"
        }
      ]
    },
    {
      "number": 7,
      "title": "Energy and Chemistry",
      "sections": [
        {
          "number": "7.1",
          "title": "Introduction",
          "ready": true,
          "file": "introductory/Energy-and-Chemistry/07-1-Introduction.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/Introductory_Chemistry/Beginning_Chemistry_(Ball)/07%3A_Energy_and_Chemistry/7.01%3A_Introduction"
        },
        {
          "number": "7.2",
          "title": "Energy",
          "ready": true,
          "file": "introductory/Energy-and-Chemistry/07-2-Energy.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/Introductory_Chemistry/Beginning_Chemistry_(Ball)/07%3A_Energy_and_Chemistry/7.02%3A_Energy"
        },
        {
          "number": "7.3",
          "title": "Work and Heat",
          "ready": true,
          "file": "introductory/Energy-and-Chemistry/07-3-Work-and-Heat.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/Introductory_Chemistry/Beginning_Chemistry_(Ball)/07%3A_Energy_and_Chemistry/7.03%3A_Work_and_Heat"
        },
        {
          "number": "7.4",
          "title": "Enthalpy and Chemical Reactions",
          "ready": true,
          "file": "introductory/Energy-and-Chemistry/07-4-Enthalpy-and-Chemical-Reactions.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/Introductory_Chemistry/Beginning_Chemistry_(Ball)/07%3A_Energy_and_Chemistry/7.04%3A_Enthalpy_and_Chemical_Reactions"
        },
        {
          "number": "7.5",
          "title": "Stoichiometry Calculations Using Enthalpy",
          "ready": true,
          "file": "introductory/Energy-and-Chemistry/07-5-Stoichiometry-Calculations-Using-Enthalpy.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/Introductory_Chemistry/Beginning_Chemistry_(Ball)/07%3A_Energy_and_Chemistry/7.05%3A_Stoichiometry_Calculations_Using_Enthalpy"
        },
        {
          "number": "7.6",
          "title": "Hess's Law",
          "ready": true,
          "file": "introductory/Energy-and-Chemistry/07-6-Hesss-Law.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/Introductory_Chemistry/Beginning_Chemistry_(Ball)/07%3A_Energy_and_Chemistry/7.06%3A_Hess's_Law"
        },
        {
          "number": "7.7",
          "title": "Formation Reactions",
          "ready": true,
          "file": "introductory/Energy-and-Chemistry/07-7-Formation-Reactions.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/Introductory_Chemistry/Beginning_Chemistry_(Ball)/07%3A_Energy_and_Chemistry/7.07%3A_Formation_Reactions"
        }
      ]
    },
    {
      "number": 8,
      "title": "Electronic Structure",
      "sections": [
        {
          "number": "8.1",
          "title": "Prelude to Electronic Structure",
          "ready": true,
          "file": "introductory/Electronic-Structure/08-1-Prelude-to-Electronic-Structure.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/Introductory_Chemistry/Beginning_Chemistry_(Ball)/08%3A_Electronic_Structure/8.01%3A_Prelude_to_Electronic_Structure"
        },
        {
          "number": "8.2",
          "title": "Light",
          "ready": true,
          "file": "introductory/Electronic-Structure/08-2-Light.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/Introductory_Chemistry/Beginning_Chemistry_(Ball)/08%3A_Electronic_Structure/8.02%3A_Light"
        },
        {
          "number": "8.3",
          "title": "Quantum Numbers for Electrons",
          "ready": true,
          "file": "introductory/Electronic-Structure/08-3-Quantum-Numbers-for-Electrons.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/Introductory_Chemistry/Beginning_Chemistry_(Ball)/08%3A_Electronic_Structure/8.03%3A_Quantum_Numbers_for_Electrons"
        },
        {
          "number": "8.4",
          "title": "Organization of Electrons in Atoms",
          "ready": true,
          "file": "introductory/Electronic-Structure/08-4-Organization-of-Electrons-in-Atoms.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/Introductory_Chemistry/Beginning_Chemistry_(Ball)/08%3A_Electronic_Structure/8.04%3A_Organization_of_Electrons_in_Atoms"
        },
        {
          "number": "8.5",
          "title": "Electronic Structure and the Periodic Table",
          "ready": true,
          "file": "introductory/Electronic-Structure/08-5-Electronic-Structure-and-the-Periodic-Table.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/Introductory_Chemistry/Beginning_Chemistry_(Ball)/08%3A_Electronic_Structure/8.05%3A_Electronic_Structure_and_the_Periodic_Table"
        },
        {
          "number": "8.6",
          "title": "Periodic Trends",
          "ready": true,
          "file": "introductory/Electronic-Structure/08-6-Periodic-Trends.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/Introductory_Chemistry/Beginning_Chemistry_(Ball)/08%3A_Electronic_Structure/8.06%3A_Periodic_Trends"
        }
      ]
    },
    {
      "number": 9,
      "title": "Chemical Bonds",
      "sections": [
        {
          "number": "9.1",
          "title": "Prelude to Chemical Bonds",
          "ready": true,
          "file": "introductory/Chemical-Bonds/09-1-Prelude-to-Chemical-Bonds.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/Introductory_Chemistry/Beginning_Chemistry_(Ball)/09%3A_Chemical_Bonds/9.01%3A_Prelude_to_Chemical_Bonds"
        },
        {
          "number": "9.2",
          "title": "Lewis Electron Dot Diagrams",
          "ready": true,
          "file": "introductory/Chemical-Bonds/09-2-Lewis-Electron-Dot-Diagrams.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/Introductory_Chemistry/Beginning_Chemistry_(Ball)/09%3A_Chemical_Bonds/9.02%3A_Lewis_Electron_Dot_Diagrams"
        },
        {
          "number": "9.3",
          "title": "Electron Transfer - Ionic Bonds",
          "ready": true,
          "file": "introductory/Chemical-Bonds/09-3-Electron-Transfer-Ionic-Bonds.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/Introductory_Chemistry/Beginning_Chemistry_(Ball)/09%3A_Chemical_Bonds/9.03%3A_Electron_Transfer_-_Ionic_Bonds"
        },
        {
          "number": "9.4",
          "title": "Covalent Bonds",
          "ready": true,
          "file": "introductory/Chemical-Bonds/09-4-Covalent-Bonds.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/Introductory_Chemistry/Beginning_Chemistry_(Ball)/09%3A_Chemical_Bonds/9.04%3A_Covalent_Bonds"
        },
        {
          "number": "9.5",
          "title": "Other Aspects of Covalent Bonds",
          "ready": true,
          "file": "introductory/Chemical-Bonds/09-5-Other-Aspects-of-Covalent-Bonds.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/Introductory_Chemistry/Beginning_Chemistry_(Ball)/09%3A_Chemical_Bonds/9.05%3A_Other_Aspects_of_Covalent_Bonds"
        },
        {
          "number": "9.6",
          "title": "Violations of the Octet Rule",
          "ready": true,
          "file": "introductory/Chemical-Bonds/09-6-Violations-of-the-Octet-Rule.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/Introductory_Chemistry/Beginning_Chemistry_(Ball)/09%3A_Chemical_Bonds/9.06%3A_Violations_of_the_Octet_Rule"
        },
        {
          "number": "9.7",
          "title": "Molecular Shapes",
          "ready": true,
          "file": "introductory/Chemical-Bonds/09-7-Molecular-Shapes.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/Introductory_Chemistry/Beginning_Chemistry_(Ball)/09%3A_Chemical_Bonds/9.07%3A_Molecular_Shapes"
        }
      ]
    },
    {
      "number": 10,
      "title": "Solids and Liquids",
      "sections": [
        {
          "number": "10.1",
          "title": "Prelude to Solids and Liquids",
          "ready": true,
          "file": "introductory/Solids-and-Liquids/10-1-Prelude-to-Solids-and-Liquids.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/Introductory_Chemistry/Beginning_Chemistry_(Ball)/10%3A_Solids_and_Liquids/10.01%3A_Prelude_to_Solids_and_Liquids"
        },
        {
          "number": "10.2",
          "title": "Intermolecular Forces",
          "ready": true,
          "file": "introductory/Solids-and-Liquids/10-2-Intermolecular-Forces.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/Introductory_Chemistry/Beginning_Chemistry_(Ball)/10%3A_Solids_and_Liquids/10.02%3A_Intermolecular_Forces"
        },
        {
          "number": "10.3",
          "title": "Phase Transitions - Melting, Boiling, and Subliming",
          "ready": true,
          "file": "introductory/Solids-and-Liquids/10-3-Phase-Transitions-Melting-Boiling-and-Subliming.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/Introductory_Chemistry/Beginning_Chemistry_(Ball)/10%3A_Solids_and_Liquids/10.03%3A_Phase_Transitions_-_Melting_Boiling_and_Subliming"
        },
        {
          "number": "10.4",
          "title": "Properties of Liquids",
          "ready": true,
          "file": "introductory/Solids-and-Liquids/10-4-Properties-of-Liquids.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/Introductory_Chemistry/Beginning_Chemistry_(Ball)/10%3A_Solids_and_Liquids/10.04%3A_Properties_of_Liquids"
        },
        {
          "number": "10.5",
          "title": "Solids",
          "ready": true,
          "file": "introductory/Solids-and-Liquids/10-5-Solids.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/Introductory_Chemistry/Beginning_Chemistry_(Ball)/10%3A_Solids_and_Liquids/10.05%3A_Solids"
        }
      ]
    },
    {
      "number": 11,
      "title": "Solutions",
      "sections": [
        {
          "number": "11.1",
          "title": "Prelude to Solutions",
          "ready": true,
          "file": "introductory/Solutions/11-1-Prelude-to-Solutions.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/Introductory_Chemistry/Beginning_Chemistry_(Ball)/11%3A_Solutions/11.01%3A_Prelude_to_Solutions"
        },
        {
          "number": "11.2",
          "title": "Definitions",
          "ready": true,
          "file": "introductory/Solutions/11-2-Definitions.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/Introductory_Chemistry/Beginning_Chemistry_(Ball)/11%3A_Solutions/11.02%3A_Definitions"
        },
        {
          "number": "11.3",
          "title": "Quantitative Units of Concentration",
          "ready": true,
          "file": "introductory/Solutions/11-3-Quantitative-Units-of-Concentration.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/Introductory_Chemistry/Beginning_Chemistry_(Ball)/11%3A_Solutions/11.03%3A_Quantitative_Units_of_Concentration"
        },
        {
          "number": "11.4",
          "title": "Dilutions and Concentrations",
          "ready": true,
          "file": "introductory/Solutions/11-4-Dilutions-and-Concentrations.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/Introductory_Chemistry/Beginning_Chemistry_(Ball)/11%3A_Solutions/11.04%3A_Dilutions_and_Concentrations"
        },
        {
          "number": "11.5",
          "title": "Concentrations as Conversion Factors",
          "ready": true,
          "file": "introductory/Solutions/11-5-Concentrations-as-Conversion-Factors.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/Introductory_Chemistry/Beginning_Chemistry_(Ball)/11%3A_Solutions/11.05%3A_Concentrations_as_Conversion_Factors"
        },
        {
          "number": "11.6",
          "title": "Colligative Properties of Solutions",
          "ready": true,
          "file": "introductory/Solutions/11-6-Colligative-Properties-of-Solutions.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/Introductory_Chemistry/Beginning_Chemistry_(Ball)/11%3A_Solutions/11.06%3A_Colligative_Properties_of_Solutions"
        },
        {
          "number": "11.7",
          "title": "Colligative Properties of Ionic Solutes",
          "ready": true,
          "file": "introductory/Solutions/11-7-Colligative-Properties-of-Ionic-Solutes.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/Introductory_Chemistry/Beginning_Chemistry_(Ball)/11%3A_Solutions/11.07%3A_Colligative_Properties_of_Ionic_Solutes"
        }
      ]
    },
    {
      "number": 12,
      "title": "Acids and Bases",
      "sections": [
        {
          "number": "12.1",
          "title": "Introduction",
          "ready": true,
          "file": "introductory/Acids-and-Bases/12-1-Introduction.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/Introductory_Chemistry/Beginning_Chemistry_(Ball)/12%3A_Acids_and_Bases/12.01%3A_Introduction"
        },
        {
          "number": "12.2",
          "title": "Arrhenius Acids and Bases",
          "ready": true,
          "file": "introductory/Acids-and-Bases/12-2-Arrhenius-Acids-and-Bases.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/Introductory_Chemistry/Beginning_Chemistry_(Ball)/12%3A_Acids_and_Bases/12.02%3A_Arrhenius_Acids_and_Bases"
        },
        {
          "number": "12.3",
          "title": "Brønsted-Lowry Acids and Bases",
          "ready": true,
          "file": "introductory/Acids-and-Bases/12-3-Bronsted-Lowry-Acids-and-Bases.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/Introductory_Chemistry/Beginning_Chemistry_(Ball)/12%3A_Acids_and_Bases/12.03%3A_Brnsted-Lowry_Acids_and_Bases"
        },
        {
          "number": "12.4",
          "title": "Acid-Base Titrations",
          "ready": true,
          "file": "introductory/Acids-and-Bases/12-4-Acid-Base-Titrations.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/Introductory_Chemistry/Beginning_Chemistry_(Ball)/12%3A_Acids_and_Bases/12.04%3A_Acid-Base_Titrations"
        },
        {
          "number": "12.5",
          "title": "Strong and Weak Acids and Bases and their Salts",
          "ready": true,
          "file": "introductory/Acids-and-Bases/12-5-Strong-and-Weak-Acids-and-Bases-and-their-Salts.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/Introductory_Chemistry/Beginning_Chemistry_(Ball)/12%3A_Acids_and_Bases/12.05%3A_Strong_and_Weak_Acids_and_Bases_and_their_Salts"
        },
        {
          "number": "12.6",
          "title": "Autoionization of Water",
          "ready": true,
          "file": "introductory/Acids-and-Bases/12-6-Autoionization-of-Water.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/Introductory_Chemistry/Beginning_Chemistry_(Ball)/12%3A_Acids_and_Bases/12.06%3A_Autoionization_of_Water"
        },
        {
          "number": "12.7",
          "title": "The pH Scale",
          "ready": true,
          "file": "introductory/Acids-and-Bases/12-7-The-pH-Scale.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/Introductory_Chemistry/Beginning_Chemistry_(Ball)/12%3A_Acids_and_Bases/12.07%3A_The_pH_Scale"
        },
        {
          "number": "12.8",
          "title": "Buffers",
          "ready": true,
          "file": "introductory/Acids-and-Bases/12-8-Buffers.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/Introductory_Chemistry/Beginning_Chemistry_(Ball)/12%3A_Acids_and_Bases/12.08%3A_Buffers"
        }
      ]
    },
    {
      "number": 13,
      "title": "Chemical Equilibrium",
      "sections": [
        {
          "number": "13.1",
          "title": "Prelude to Chemical Equilibrium",
          "ready": true,
          "file": "introductory/Chemical-Equilibrium/13-1-Prelude-to-Chemical-Equilibrium.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/Introductory_Chemistry/Beginning_Chemistry_(Ball)/13%3A_Chemical_Equilibrium/13.01%3A_Prelude_to_Chemical_Equilibrium"
        },
        {
          "number": "13.2",
          "title": "Chemical Equilibrium",
          "ready": true,
          "file": "introductory/Chemical-Equilibrium/13-2-Chemical-Equilibrium.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/Introductory_Chemistry/Beginning_Chemistry_(Ball)/13%3A_Chemical_Equilibrium/13.02%3A_Chemical_Equilibrium"
        },
        {
          "number": "13.3",
          "title": "The Equilibrium Constant",
          "ready": true,
          "file": "introductory/Chemical-Equilibrium/13-3-The-Equilibrium-Constant.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/Introductory_Chemistry/Beginning_Chemistry_(Ball)/13%3A_Chemical_Equilibrium/13.03%3A_The_Equilibrium_Constant"
        },
        {
          "number": "13.4",
          "title": "Shifting Equilibria - Le Chatelier's Principle",
          "ready": true,
          "file": "introductory/Chemical-Equilibrium/13-4-Shifting-Equilibria-Le-Chateliers-Principle.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/Introductory_Chemistry/Beginning_Chemistry_(Ball)/13%3A_Chemical_Equilibrium/13.04%3A_Shifting_Equilibria_-_Le_Chatelier's_Principle"
        },
        {
          "number": "13.5",
          "title": "Calculating Equilibrium Constant Values",
          "ready": true,
          "file": "introductory/Chemical-Equilibrium/13-5-Calculating-Equilibrium-Constant-Values.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/Introductory_Chemistry/Beginning_Chemistry_(Ball)/13%3A_Chemical_Equilibrium/13.05%3A_Calculating_Equilibrium_Constant_Values"
        },
        {
          "number": "13.6",
          "title": "Some Special Types of Equilibria",
          "ready": true,
          "file": "introductory/Chemical-Equilibrium/13-6-Some-Special-Types-of-Equilibria.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/Introductory_Chemistry/Beginning_Chemistry_(Ball)/13%3A_Chemical_Equilibrium/13.06%3A_Some_Special_Types_of_Equilibria"
        }
      ]
    },
    {
      "number": 14,
      "title": "Oxidation and Reduction",
      "sections": [
        {
          "number": "14.1",
          "title": "Introduction to Oxidation and Reduction",
          "ready": true,
          "file": "introductory/Oxidation-and-Reduction/14-1-Introduction-to-Oxidation-and-Reduction.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/Introductory_Chemistry/Beginning_Chemistry_(Ball)/14%3A_Oxidation_and_Reduction/14.01%3A_Introduction_to_Oxidation_and_Reduction"
        },
        {
          "number": "14.2",
          "title": "Oxidation-Reduction Reactions",
          "ready": true,
          "file": "introductory/Oxidation-and-Reduction/14-2-Oxidation-Reduction-Reactions.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/Introductory_Chemistry/Beginning_Chemistry_(Ball)/14%3A_Oxidation_and_Reduction/14.02%3A_Oxidation-Reduction_Reactions"
        },
        {
          "number": "14.3",
          "title": "Balancing Redox Reactions",
          "ready": true,
          "file": "introductory/Oxidation-and-Reduction/14-3-Balancing-Redox-Reactions.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/Introductory_Chemistry/Beginning_Chemistry_(Ball)/14%3A_Oxidation_and_Reduction/14.03%3A_Balancing_Redox_Reactions"
        },
        {
          "number": "14.4",
          "title": "Applications of Redox Reactions - Voltaic Cells",
          "ready": true,
          "file": "introductory/Oxidation-and-Reduction/14-4-Applications-of-Redox-Reactions-Voltaic-Cells.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/Introductory_Chemistry/Beginning_Chemistry_(Ball)/14%3A_Oxidation_and_Reduction/14.04%3A_Applications_of_Redox_Reactions_-_Voltaic_Cells"
        },
        {
          "number": "14.5",
          "title": "Electrolysis",
          "ready": true,
          "file": "introductory/Oxidation-and-Reduction/14-5-Electrolysis.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/Introductory_Chemistry/Beginning_Chemistry_(Ball)/14%3A_Oxidation_and_Reduction/14.05%3A_Electrolysis"
        }
      ]
    },
    {
      "number": 15,
      "title": "Nuclear Chemistry",
      "sections": [
        {
          "number": "15.1",
          "title": "Prelude to Nuclear Chemistry",
          "ready": true,
          "file": "introductory/Nuclear-Chemistry/15-1-Prelude-to-Nuclear-Chemistry.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/Introductory_Chemistry/Beginning_Chemistry_(Ball)/15%3A_Nuclear_Chemistry/15.01%3A_Prelude_to_Nuclear_Chemistry"
        },
        {
          "number": "15.2",
          "title": "Radioactivity",
          "ready": true,
          "file": "introductory/Nuclear-Chemistry/15-2-Radioactivity.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/Introductory_Chemistry/Beginning_Chemistry_(Ball)/15%3A_Nuclear_Chemistry/15.02%3A_Radioactivity"
        },
        {
          "number": "15.3",
          "title": "Half-Life",
          "ready": true,
          "file": "introductory/Nuclear-Chemistry/15-3-Half-Life.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/Introductory_Chemistry/Beginning_Chemistry_(Ball)/15%3A_Nuclear_Chemistry/15.03%3A_Half-Life"
        },
        {
          "number": "15.4",
          "title": "Units of Radioactivity",
          "ready": true,
          "file": "introductory/Nuclear-Chemistry/15-4-Units-of-Radioactivity.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/Introductory_Chemistry/Beginning_Chemistry_(Ball)/15%3A_Nuclear_Chemistry/15.04%3A_Units_of_Radioactivity"
        },
        {
          "number": "15.5",
          "title": "Uses of Radioactive Isotopes",
          "ready": true,
          "file": "introductory/Nuclear-Chemistry/15-5-Uses-of-Radioactive-Isotopes.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/Introductory_Chemistry/Beginning_Chemistry_(Ball)/15%3A_Nuclear_Chemistry/15.05%3A_Uses_of_Radioactive_Isotopes"
        },
        {
          "number": "15.6",
          "title": "Nuclear Energy",
          "ready": true,
          "file": "introductory/Nuclear-Chemistry/15-6-Nuclear-Energy.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/Introductory_Chemistry/Beginning_Chemistry_(Ball)/15%3A_Nuclear_Chemistry/15.06%3A_Nuclear_Energy"
        }
      ]
    },
    {
      "number": 16,
      "title": "Organic Chemistry",
      "sections": [
        {
          "number": "16.1",
          "title": "Prelude to Organic Chemistry",
          "ready": true,
          "file": "introductory/Organic-Chemistry/16-1-Prelude-to-Organic-Chemistry.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/Introductory_Chemistry/Beginning_Chemistry_(Ball)/16%3A_Organic_Chemistry/16.01%3A_Prelude_to_Organic_Chemistry"
        },
        {
          "number": "16.2",
          "title": "Hydrocarbons",
          "ready": true,
          "file": "introductory/Organic-Chemistry/16-2-Hydrocarbons.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/Introductory_Chemistry/Beginning_Chemistry_(Ball)/16%3A_Organic_Chemistry/16.02%3A_Hydrocarbons"
        },
        {
          "number": "16.3",
          "title": "Branched Hydrocarbons",
          "ready": true,
          "file": "introductory/Organic-Chemistry/16-3-Branched-Hydrocarbons.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/Introductory_Chemistry/Beginning_Chemistry_(Ball)/16%3A_Organic_Chemistry/16.03%3A_Branched_Hydrocarbons"
        },
        {
          "number": "16.4",
          "title": "Alkyl Halides and Alcohols",
          "ready": true,
          "file": "introductory/Organic-Chemistry/16-4-Alkyl-Halides-and-Alcohols.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/Introductory_Chemistry/Beginning_Chemistry_(Ball)/16%3A_Organic_Chemistry/16.04%3A_Alkyl_Halides_and_Alcohols"
        },
        {
          "number": "16.5",
          "title": "Other Oxygen-Containing Functional Groups",
          "ready": true,
          "file": "introductory/Organic-Chemistry/16-5-Other-Oxygen-Containing-Functional-Groups.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/Introductory_Chemistry/Beginning_Chemistry_(Ball)/16%3A_Organic_Chemistry/16.05%3A_Other_Oxygen-Containing_Functional_Groups"
        },
        {
          "number": "16.6",
          "title": "Other Functional Groups",
          "ready": true,
          "file": "introductory/Organic-Chemistry/16-6-Other-Functional-Groups.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/Introductory_Chemistry/Beginning_Chemistry_(Ball)/16%3A_Organic_Chemistry/16.06%3A_Other_Functional_Groups"
        },
        {
          "number": "16.7",
          "title": "Polymers",
          "ready": true,
          "file": "introductory/Organic-Chemistry/16-7-Polymers.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/Introductory_Chemistry/Beginning_Chemistry_(Ball)/16%3A_Organic_Chemistry/16.07%3A_Polymers"
        }
      ]
    }
  ],
  "chemistry-1e": [
    {
      "number": 1,
      "title": "Essential Ideas of Chemistry",
      "sections": [
        {
          "number": "1.1",
          "title": "Chemistry in Context",
          "ready": true,
          "file": "genchem-1e/Essential-Ideas-of-Chemistry/01-1-chemistry-in-context.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/General_Chemistry/Chemistry_1e_(OpenSTAX)/01%3A_Essential_Ideas_of_Chemistry/1.1%3A_Chemistry_in_Context"
        },
        {
          "number": "1.2",
          "title": "Phases and Classification of Matter",
          "ready": true,
          "file": "genchem-1e/Essential-Ideas-of-Chemistry/01-2-Phases and Classification of Matter.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/General_Chemistry/Chemistry_1e_(OpenSTAX)/01%3A_Essential_Ideas_of_Chemistry/1.02%3A_Phases_and_Classification_of_Matter"
        },
        {
          "number": "1.3",
          "title": "Physical and Chemical Properties",
          "ready": true,
          "file": "genchem-1e/Essential-Ideas-of-Chemistry/01-3-Physical-and-Chemical-Properties.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/General_Chemistry/Chemistry_1e_(OpenSTAX)/01%3A_Essential_Ideas_of_Chemistry/1.03%3A_Physical_and_Chemical_Properties"
        },
        {
          "number": "1.4",
          "title": "Measurements",
          "ready": true,
          "file": "genchem-1e/Essential-Ideas-of-Chemistry/01-4-Measurements.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/General_Chemistry/Chemistry_1e_(OpenSTAX)/01%3A_Essential_Ideas_of_Chemistry/1.04%3A_Measurements"
        },
        {
          "number": "1.4",
          "title": "Measurement Uncertainty, Accuracy, and Precision",
          "ready": true,
          "file": "genchem-1e/Essential-Ideas-of-Chemistry/01-5-Measurement-Uncertainty-Accuracy-Precision.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/General_Chemistry/Chemistry_1e_(OpenSTAX)/01%3A_Essential_Ideas_of_Chemistry/1.05%3A_Measurement_Uncertainty_Accuracy_and_Precision"
        },
        {
          "number": "1.6",
          "title": "Mathematical Treatment of Measurement Results",
          "ready": true,
          "file": "genchem-1e/Essential-Ideas-of-Chemistry/01-6-Mathematical-Treatment-of-Measurement-Results.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/General_Chemistry/Chemistry_1e_(OpenSTAX)/01%3A_Essential_Ideas_of_Chemistry/1.06%3A_Mathematical_Treatment_of_Measurement_Results"
        }
      ]
    },
    {
      "number": 2,
      "title": "Atoms, Molecules, and Ions",
      "sections": [
        {
          "number": "2.1",
          "title": "Prelude to Atoms",
          "ready": true,
          "file": "genchem-1e/Atoms-Molecules-Ions/02-1-Prelude-to-Atoms.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/General_Chemistry/Chemistry_1e_(OpenSTAX)/02%3A_Atoms_Molecules_and_Ions/2.01%3A_Prelude_to_Atoms"
        },
        {
          "number": "2.2",
          "title": "Early Ideas in Atomic Theory",
          "ready": true,
          "file": "genchem-1e/Atoms-Molecules-Ions/02-2-Early-Ideas-in-Atomic-Theory.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/General_Chemistry/Chemistry_1e_(OpenSTAX)/02%3A_Atoms_Molecules_and_Ions/2.02%3A_Early_Ideas_in_Atomic_Theory"
        },
        {
          "number": "2.3",
          "title": "Evolution of Atomic Theory",
          "ready": true,
          "file": "genchem-1e/Atoms-Molecules-Ions/02-3-Evolution-of-Atomic-Theory.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/General_Chemistry/Chemistry_1e_(OpenSTAX)/02%3A_Atoms_Molecules_and_Ions/2.02%3A_Early_Ideas_in_Atomic_Theory"
        },
        {
          "number": "2.4",
          "title": "Atomic Structure and Symbolism",
          "ready": true,
          "file": "genchem-1e/Atoms-Molecules-Ions/02-4-Atomic-Structure-and-Symbolism.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/General_Chemistry/Chemistry_1e_(OpenSTAX)/02%3A_Atoms_Molecules_and_Ions/2.02%3A_Early_Ideas_in_Atomic_Theory"
        },
        {
          "number": "2.5",
          "title": "Chemical Formulas",
          "ready": true,
          "file": "genchem-1e/Atoms-Molecules-Ions/02-5-Chemical-Formulas.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/General_Chemistry/Chemistry_1e_(OpenSTAX)/02%3A_Atoms_Molecules_and_Ions/2.02%3A_Early_Ideas_in_Atomic_Theory"
        },
        {
          "number": "2.6",
          "title": "The Periodic Table",
          "ready": true,
          "file": "genchem-1e/Atoms-Molecules-Ions/02-6-The-Periodic-Table.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/General_Chemistry/Chemistry_1e_(OpenSTAX)/02%3A_Atoms_Molecules_and_Ions/2.02%3A_Early_Ideas_in_Atomic_Theory"
        },
        {
          "number": "2.7",
          "title": "Molecular and Ionic Compounds",
          "ready": true,
          "file": "genchem-1e/Atoms-Molecules-Ions/02-7-Molecular-and-Ionic-Compounds.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/General_Chemistry/Chemistry_1e_(OpenSTAX)/02%3A_Atoms_Molecules_and_Ions/2.07%3A_Molecular_and_Ionic_Compounds"
        },
        {
          "number": "2.8",
          "title": "Chemical Nomenclature",
          "ready": true,
          "file": "genchem-1e/Atoms-Molecules-Ions/02-8-Chemical-Nomenclature.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/General_Chemistry/Chemistry_1e_(OpenSTAX)/02%3A_Atoms_Molecules_and_Ions/2.08%3A_Chemical_Nomenclature"
        }
      ]
    },
    {
      "number": 3,
      "title": "Composition of Substances and Solutions",
      "sections": [
        {
          "number": "3.1",
          "title": "Formula Mass and the Mole Concept",
          "ready": true,
          "file": "genchem-1e/Composition-of-Substance-and-Solutions/03-1-Formula-mass-and-the-mole-Concept.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/General_Chemistry/Chemistry_1e_(OpenSTAX)/03%3A_Composition_of_Substances_and_Solutions/3.01%3A_Formula_Mass_and_the_Mole_Concept"
        },
        {
          "number": "3.2",
          "title": "Determining Empirical and Molecular Formulas",
          "ready": true,
          "file": "genchem-1e/Composition-of-Substance-and-Solutions/03-2-Determining-Molecular-Formulas.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/General_Chemistry/Chemistry_1e_(OpenSTAX)/03%3A_Composition_of_Substances_and_Solutions/3.02%3A_Determining_Empirical_and_Molecular_Formulas"
        },
        {
          "number": "3.3",
          "title": "Molarity",
          "ready": true,
          "file": "genchem-1e/Composition-of-Substance-and-Solutions/03-3-Molarity.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/General_Chemistry/Chemistry_1e_(OpenSTAX)/03%3A_Composition_of_Substances_and_Solutions/3.03%3A_Molarity"
        },
        {
          "number": "3.4",
          "title": "Other Units for Solution Concentrations",
          "ready": true,
          "file": "genchem-1e/Composition-of-Substance-and-Solutions/03-4-Other-units-for-Solution-Concentrations.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/General_Chemistry/Chemistry_1e_(OpenSTAX)/03%3A_Composition_of_Substances_and_Solutions/3.04%3A_Other_Units_for_Solution_Concentrations"
        }
      ]
    },
    {
      "number": 4,
      "title": "Stoichiometry of Chemical Reactions",
      "sections": [
        {
          "number": "4.1",
          "title": "Prelude to Stoichiometry",
          "ready": true,
          "file": "genchem-1e/Stoichiometry-of-Chemical-Reactions/04-1-Prelude-to-Stoichiometry.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/General_Chemistry/Chemistry_1e_(OpenSTAX)/04%3A_Stoichiometry_of_Chemical_Reactions/4.01%3A_Prelude_to_Stoichiometry"
        },
        {
          "number": "4.2",
          "title": "Writing and Balancing Chemical Equations",
          "ready": true,
          "file": "genchem-1e/Stoichiometry-of-Chemical-Reactions/04-2-Writing-and-Balancing-Chemical-Equations.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/General_Chemistry/Chemistry_1e_(OpenSTAX)/04%3A_Stoichiometry_of_Chemical_Reactions/4.02%3A_Writing_and_Balancing_Chemical_Equations"
        },
        {
          "number": "4.3",
          "title": "Classifying Chemical Reactions",
          "ready": true,
          "file": "genchem-1e/Stoichiometry-of-Chemical-Reactions/04-3-Classifying-Chemical-Reactions.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/General_Chemistry/Chemistry_1e_(OpenSTAX)/04%3A_Stoichiometry_of_Chemical_Reactions/4.03%3A_Classifying_Chemical_Reactions"
        },
        {
          "number": "4.4",
          "title": "Reaction Stoichiometry",
          "ready": true,
          "file": "genchem-1e/Stoichiometry-of-Chemical-Reactions/04-4-Reaction-Stoichiometry.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/General_Chemistry/Chemistry_1e_(OpenSTAX)/04%3A_Stoichiometry_of_Chemical_Reactions/4.04%3A_Reaction_Stoichiometry"
        },
        {
          "number": "4.5",
          "title": "Reaction Yields",
          "ready": true,
          "file": "genchem-1e/Stoichiometry-of-Chemical-Reactions/04-5-Reaction-Yields.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/General_Chemistry/Chemistry_1e_(OpenSTAX)/04%3A_Stoichiometry_of_Chemical_Reactions/4.05%3A_Reaction_Yields"
        },
        {
          "number": "4.6",
          "title": "Quantitative Chemical Analysis",
          "ready": true,
          "file": "genchem-1e/Stoichiometry-of-Chemical-Reactions/04-6-Quantitative-Chemical-Analysis.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/General_Chemistry/Chemistry_1e_(OpenSTAX)/04%3A_Stoichiometry_of_Chemical_Reactions/4.06%3A_Quantitative_Chemical_Analysis"
        }
      ]
    },
    {
      "number": 5,
      "title": "Thermochemistry",
      "sections": [
        {
          "number": "5.1",
          "title": "Prelude to Thermochemistry",
          "ready": true,
          "file": "genchem-1e/Thermochemistry/05-1-Prelude-to-Thermochemistry.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/General_Chemistry/Chemistry_1e_(OpenSTAX)/05%3A_Thermochemistry/5.01%3A_Prelude_to_Thermochemistry"
        },
        {
          "number": "5.2",
          "title": "Energy Basics",
          "ready": true,
          "file": "genchem-1e/Thermochemistry/05-2-Energy-Basics.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/General_Chemistry/Chemistry_1e_(OpenSTAX)/05%3A_Thermochemistry/5.02%3A_Energy_Basics"
        },
        {
          "number": "5.3",
          "title": "Calorimetry",
          "ready": true,
          "file": "genchem-1e/Thermochemistry/05-3-Calorimetry.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/General_Chemistry/Chemistry_1e_(OpenSTAX)/05%3A_Thermochemistry/5.03%3A_Calorimetry"
        },
        {
          "number": "5.4",
          "title": "Enthalpy",
          "ready": true,
          "file": "genchem-1e/Thermochemistry/05-4-Enthalpy.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/General_Chemistry/Chemistry_1e_(OpenSTAX)/05%3A_Thermochemistry/5.04%3A_Enthalpy"
        }
      ]
    },
    {
      "number": 6,
      "title": "Electronic Structure and Periodic Properties",
      "sections": [
        {
          "number": "6.1",
          "title": "Electromagnetic Energy",
          "ready": true,
          "file": "genchem-1e/Electronic-Structure-and-Periodic-Properties/06-1-Electromagnetic-Energy.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/General_Chemistry/Chemistry_1e_(OpenSTAX)/06%3A_Electronic_Structure_and_Periodic_Properties/6.01%3A_Electromagnetic_Energy"
        },
        {
          "number": "6.2",
          "title": "The Bohr Model",
          "ready": true,
          "file": "genchem-1e/Electronic-Structure-and-Periodic-Properties/06-2-The-Bohr-Model.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/General_Chemistry/Chemistry_1e_(OpenSTAX)/06%3A_Electronic_Structure_and_Periodic_Properties/6.02%3A_The_Bohr_Model"
        },
        {
          "number": "6.3",
          "title": "Development of Quantum Theory",
          "ready": true,
          "file": "genchem-1e/Electronic-Structure-and-Periodic-Properties/06-3-Development-of-Quantum-Theory.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/General_Chemistry/Chemistry_1e_(OpenSTAX)/06%3A_Electronic_Structure_and_Periodic_Properties/6.03%3A_Development_of_Quantum_Theory"
        },
        {
          "number": "6.4",
          "title": "Electronic Structure of Atoms (Electron Configurations)",
          "ready": true,
          "file": "genchem-1e/Electronic-Structure-and-Periodic-Properties/06-4-Electronic-Structure-of-Atoms.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/General_Chemistry/Chemistry_1e_(OpenSTAX)/06%3A_Electronic_Structure_and_Periodic_Properties/6.04%3A_Electronic_Structure_of_Atoms_(Electron_Configurations)"
        },
        {
          "number": "6.5",
          "title": "Periodic Variations in Element Properties",
          "ready": true,
          "file": "genchem-1e/Electronic-Structure-and-Periodic-Properties/06-5-Periodic-Variations-in-Element-Properties.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/General_Chemistry/Chemistry_1e_(OpenSTAX)/06%3A_Electronic_Structure_and_Periodic_Properties/6.05%3A_Periodic_Variations_in_Element_Properties"
        }
      ]
    },
    {
      "number": 7,
      "title": "Chemical Bonding and Molecular Geometry",
      "sections": [
        {
          "number": "7.1",
          "title": "Prelude to Chemical Bonding and Molecular Geometry",
          "ready": true,
          "file": "genchem-1e/Chemical-Bonding-and-Molecular-Geometry/07-1-Prelude-to-Chemical-Bonding.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/General_Chemistry/Chemistry_1e_(OpenSTAX)/07%3A_Chemical_Bonding_and_Molecular_Geometry/7.01%3A_Prelude_to_Chemical_Bonding_and_Molecular_Geometry"
        },
        {
          "number": "7.2",
          "title": "Ionic Bonding",
          "ready": true,
          "file": "genchem-1e/Chemical-Bonding-and-Molecular-Geometry/07-2-Ionic-Bonding.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/General_Chemistry/Chemistry_1e_(OpenSTAX)/07%3A_Chemical_Bonding_and_Molecular_Geometry/7.02%3A_Ionic_Bonding"
        },
        {
          "number": "7.3",
          "title": "Covalent Bonding",
          "ready": true,
          "file": "genchem-1e/Chemical-Bonding-and-Molecular-Geometry/07-3-Covalent-Bonding.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/General_Chemistry/Chemistry_1e_(OpenSTAX)/07%3A_Chemical_Bonding_and_Molecular_Geometry/7.03%3A_Covalent_Bonding"
        },
        {
          "number": "7.4",
          "title": "Lewis Symbols and Structures",
          "ready": true,
          "file": "genchem-1e/Chemical-Bonding-and-Molecular-Geometry/07-4-Lewis-Symbols-and-Structures.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/General_Chemistry/Chemistry_1e_(OpenSTAX)/07%3A_Chemical_Bonding_and_Molecular_Geometry/7.04%3A_Lewis_Symbols_and_Structures"
        },
        {
          "number": "7.5",
          "title": "Formal Charges and Resonance",
          "ready": true,
          "file": "genchem-1e/Chemical-Bonding-and-Molecular-Geometry/07-5-Formal-Charges-and-Resonance.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/General_Chemistry/Chemistry_1e_(OpenSTAX)/07%3A_Chemical_Bonding_and_Molecular_Geometry/7.05%3A_Formal_Charges_and_Resonance"
        },
        {
          "number": "7.6",
          "title": "Strengths of Ionic and Covalent Bonds",
          "ready": true,
          "file": "genchem-1e/Chemical-Bonding-and-Molecular-Geometry/07-6-Strengths-of-Ionic-and-Covalent-Bonds.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/General_Chemistry/Chemistry_1e_(OpenSTAX)/07%3A_Chemical_Bonding_and_Molecular_Geometry/7.06%3A_Strengths_of_Ionic_and_Covalent_Bonds"
        },
        {
          "number": "7.7",
          "title": "Molecular Structure and Polarity",
          "ready": true,
          "file": "genchem-1e/Chemical-Bonding-and-Molecular-Geometry/07-7-Molecular-Structure-and-Polarity.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/General_Chemistry/Chemistry_1e_(OpenSTAX)/07%3A_Chemical_Bonding_and_Molecular_Geometry/7.07%3A_Molecular_Structure_and_Polarity"
        }
      ]
    },
    {
      "number": 8,
      "title": "Advanced Theories of Covalent Bonding",
      "sections": [
        {
          "number": "8.1",
          "title": "Prelude to Covalent Bonding",
          "ready": true,
          "file": "genchem-1e/Advanced-Theories-of-Covalent-Bonding/08-1-Prelude-to-Covalent-Bonding.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/General_Chemistry/Chemistry_1e_(OpenSTAX)/08%3A_Advanced_Theories_of_Covalent_Bonding/8.01%3A_Prelude_to_Covalent_Bonding"
        },
        {
          "number": "8.2",
          "title": "Valence Bond Theory",
          "ready": true,
          "file": "genchem-1e/Advanced-Theories-of-Covalent-Bonding/08-2-Valence-Bond-Theory.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/General_Chemistry/Chemistry_1e_(OpenSTAX)/08%3A_Advanced_Theories_of_Covalent_Bonding/8.02%3A_Valence_Bond_Theory"
        },
        {
          "number": "8.3",
          "title": "Hybrid Atomic Orbitals",
          "ready": true,
          "file": "genchem-1e/Advanced-Theories-of-Covalent-Bonding/08-3-Hybrid-Atomic-Orbitals.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/General_Chemistry/Chemistry_1e_(OpenSTAX)/08%3A_Advanced_Theories_of_Covalent_Bonding/8.03%3A_Hybrid_Atomic_Orbitals"
        },
        {
          "number": "8.4",
          "title": "Multiple Bonds",
          "ready": true,
          "file": "genchem-1e/Advanced-Theories-of-Covalent-Bonding/08-4-Multiple-Bonds.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/General_Chemistry/Chemistry_1e_(OpenSTAX)/08%3A_Advanced_Theories_of_Covalent_Bonding/8.04%3A_Multiple_Bonds"
        },
        {
          "number": "8.5",
          "title": "Molecular Orbital Theory",
          "ready": true,
          "file": "genchem-1e/Advanced-Theories-of-Covalent-Bonding/08-5-Molecular-Orbital-Theory.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/General_Chemistry/Chemistry_1e_(OpenSTAX)/08%3A_Advanced_Theories_of_Covalent_Bonding/8.05%3A_Molecular_Orbital_Theory"
        }
      ]
    },
    {
      "number": 9,
      "title": "Gases",
      "sections": [
        {
          "number": "9.1",
          "title": "Gas Pressure",
          "ready": true,
          "file": "genchem-1e/Gases/09-1-Gas-Pressure.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/General_Chemistry/Chemistry_1e_(OpenSTAX)/09%3A_Gases/9.01%3A_Gas_Pressure"
        },
        {
          "number": "9.2",
          "title": "Relating Pressure, Volume, Amount, and Temperature - The Ideal Gas Law",
          "ready": true,
          "file": "genchem-1e/Gases/09-2-Relating-Pressure-Volume-Amount-and-Temperature.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/General_Chemistry/Chemistry_1e_(OpenSTAX)/09%3A_Gases/9.02%3A_Relating_Pressure_Volume_Amount_and_Temperature_-_The_Ideal_Gas_Law"
        },
        {
          "number": "9.3",
          "title": "Stoichiometry of Gaseous Substances, Mixtures, and Reactions",
          "ready": true,
          "file": "genchem-1e/Gases/09-3-Stoichiometry-of-Gaseous-Substances-Mixtures-and-Reactions.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/General_Chemistry/Chemistry_1e_(OpenSTAX)/09%3A_Gases/9.03%3A_Stoichiometry_of_Gaseous_Substances_Mixtures_and_Reactions"
        },
        {
          "number": "9.4",
          "title": "Effusion and Diffusion of Gases",
          "ready": true,
          "file": "genchem-1e/Gases/09-4-Effusion-and-Diffusion-of-Gases.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/General_Chemistry/Chemistry_1e_(OpenSTAX)/09%3A_Gases/9.04%3A_Effusion_and_Diffusion_of_Gases"
        },
        {
          "number": "9.5",
          "title": "The Kinetic-Molecular Theory",
          "ready": true,
          "file": "genchem-1e/Gases/09-5-The-Kinetic-Molecular-Theory.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/General_Chemistry/Chemistry_1e_(OpenSTAX)/09%3A_Gases/9.05%3A_The_Kinetic-Molecular_Theory"
        },
        {
          "number": "9.6",
          "title": "Non-Ideal Gas Behavior",
          "ready": true,
          "file": "genchem-1e/Gases/09-6-Non-Ideal-Gas-Behavior.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/General_Chemistry/Chemistry_1e_(OpenSTAX)/09%3A_Gases/9.06%3A_Non-Ideal_Gas_Behavior"
        }
      ]
    },
    {
      "number": 10,
      "title": "Liquids and Solids",
      "sections": [
        {
          "number": "10.1",
          "title": "Prelude to Liquids and Solids",
          "ready": true,
          "file": "genchem-1e/Liquids-and-Solids/10-1-Prelude-to-Liquids-and-Solids.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/General_Chemistry/Chemistry_1e_(OpenSTAX)/10%3A_Liquids_and_Solids/10.01%3A_Prelude_to_Liquids_and_Solids"
        },
        {
          "number": "10.2",
          "title": "Intermolecular Forces",
          "ready": true,
          "file": "genchem-1e/Liquids-and-Solids/10-2-Intermolecular-Forces.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/General_Chemistry/Chemistry_1e_(OpenSTAX)/10%3A_Liquids_and_Solids/10.02%3A_Intermolecular_Forces"
        },
        {
          "number": "10.3",
          "title": "Properties of Liquids",
          "ready": true,
          "file": "genchem-1e/Liquids-and-Solids/10-3-Properties-of-Liquids.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/General_Chemistry/Chemistry_1e_(OpenSTAX)/10%3A_Liquids_and_Solids/10.03%3A_Properties_of_Liquids"
        },
        {
          "number": "10.4",
          "title": "Phase Transitions",
          "ready": true,
          "file": "genchem-1e/Liquids-and-Solids/10-4-Phase-Transitions.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/General_Chemistry/Chemistry_1e_(OpenSTAX)/10%3A_Liquids_and_Solids/10.04%3A_Phase_Transitions"
        },
        {
          "number": "10.5",
          "title": "Phase Diagrams",
          "ready": true,
          "file": "genchem-1e/Liquids-and-Solids/10-5-Phase-Diagrams.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/General_Chemistry/Chemistry_1e_(OpenSTAX)/10%3A_Liquids_and_Solids/10.05%3A_Phase_Diagrams"
        },
        {
          "number": "10.6",
          "title": "The Solid State of Matter",
          "ready": true,
          "file": "genchem-1e/Liquids-and-Solids/10-6-The-Solid-State-of-Matter.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/General_Chemistry/Chemistry_1e_(OpenSTAX)/10%3A_Liquids_and_Solids/10.06%3A_The_Solid_State_of_Matter"
        },
        {
          "number": "10.7",
          "title": "Lattice Structures in Crystalline Solids",
          "ready": true,
          "file": "genchem-1e/Liquids-and-Solids/10-7-Lattice-Structures-in-Crystalline-Solids.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/General_Chemistry/Chemistry_1e_(OpenSTAX)/10%3A_Liquids_and_Solids/10.07%3A_Lattice_Structures_in_Crystalline_Solids"
        }
      ]
    },
    {
      "number": 11,
      "title": "Solutions and Colloids",
      "sections": [
        {
          "number": "11.1",
          "title": "Prelude to Solutions and Colloids",
          "ready": true,
          "file": "genchem-1e/Solutions-and-Colloids/11-1-Prelude-to-Solutions-and-Colloids.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/General_Chemistry/Chemistry_1e_(OpenSTAX)/11%3A_Solutions_and_Colloids/11.01%3A_Prelude_to_Solutions_and_Colloids"
        },
        {
          "number": "11.2",
          "title": "The Dissolution Process",
          "ready": true,
          "file": "genchem-1e/Solutions-and-Colloids/11-2-The-Dissolution-Process.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/General_Chemistry/Chemistry_1e_(OpenSTAX)/11%3A_Solutions_and_Colloids/11.02%3A_The_Dissolution_Process"
        },
        {
          "number": "11.3",
          "title": "Electrolytes",
          "ready": true,
          "file": "genchem-1e/Solutions-and-Colloids/11-3-Electrolytes.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/General_Chemistry/Chemistry_1e_(OpenSTAX)/11%3A_Solutions_and_Colloids/11.03%3A_Electrolytes"
        },
        {
          "number": "11.4",
          "title": "Solubility",
          "ready": true,
          "file": "genchem-1e/Solutions-and-Colloids/11-4-Solubility.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/General_Chemistry/Chemistry_1e_(OpenSTAX)/11%3A_Solutions_and_Colloids/11.04%3A_Solubility"
        },
        {
          "number": "11.5",
          "title": "Colligative Properties",
          "ready": true,
          "file": "genchem-1e/Solutions-and-Colloids/11-5-Colligative-Properties.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/General_Chemistry/Chemistry_1e_(OpenSTAX)/11%3A_Solutions_and_Colloids/11.05%3A_Colligative_Properties"
        },
        {
          "number": "11.6",
          "title": "Colloids",
          "ready": true,
          "file": "genchem-1e/Solutions-and-Colloids/11-6-Colloids.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/General_Chemistry/Chemistry_1e_(OpenSTAX)/11%3A_Solutions_and_Colloids/11.06%3A_Colloids"
        }
      ]
    },
    {
      "number": 12,
      "title": "Kinetics",
      "sections": [
        {
          "number": "12.1",
          "title": "Prelude to Kinetics",
          "ready": true,
          "file": "genchem-1e/Kinetics/12-1-Prelude-to-Kinetics.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/General_Chemistry/Chemistry_1e_(OpenSTAX)/12%3A_Kinetics/12.01%3A_Prelude_to_Kinetics"
        },
        {
          "number": "12.2",
          "title": "Chemical Reaction Rates",
          "ready": true,
          "file": "genchem-1e/Kinetics/12-2-Chemical-Reaction-Rates.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/General_Chemistry/Chemistry_1e_(OpenSTAX)/12%3A_Kinetics/12.02%3A_Chemical_Reaction_Rates"
        },
        {
          "number": "12.3",
          "title": "Factors Affecting Reaction Rates",
          "ready": true,
          "file": "genchem-1e/Kinetics/12-3-Factors-Affecting-Reaction-Rates.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/General_Chemistry/Chemistry_1e_(OpenSTAX)/12%3A_Kinetics/12.03%3A_Factors_Affecting_Reaction_Rates"
        },
        {
          "number": "12.4",
          "title": "Rate Laws",
          "ready": true,
          "file": "genchem-1e/Kinetics/12-4-Rate-Laws.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/General_Chemistry/Chemistry_1e_(OpenSTAX)/12%3A_Kinetics/12.04%3A_Rate_Laws"
        },
        {
          "number": "12.5",
          "title": "Integrated Rate Laws",
          "ready": true,
          "file": "genchem-1e/Kinetics/12-5-Integrated-Rate-Laws.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/General_Chemistry/Chemistry_1e_(OpenSTAX)/12%3A_Kinetics/12.05%3A_Integrated_Rate_Laws"
        },
        {
          "number": "12.6",
          "title": "Collision Theory",
          "ready": true,
          "file": "genchem-1e/Kinetics/12-6-Collision-Theory.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/General_Chemistry/Chemistry_1e_(OpenSTAX)/12%3A_Kinetics/12.06%3A_Collision_Theory"
        },
        {
          "number": "12.7",
          "title": "Reaction Mechanisms",
          "ready": true,
          "file": "genchem-1e/Kinetics/12-7-Reaction-Mechanisms.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/General_Chemistry/Chemistry_1e_(OpenSTAX)/12%3A_Kinetics/12.07%3A_Reaction_Mechanisms"
        },
        {
          "number": "12.8",
          "title": "Catalysis",
          "ready": true,
          "file": "genchem-1e/Kinetics/12-8-Catalysis.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/General_Chemistry/Chemistry_1e_(OpenSTAX)/12%3A_Kinetics/12.08%3A_Catalysis"
        }
      ]
    },
    {
      "number": 13,
      "title": "Fundamental Equilibrium Concepts",
      "sections": [
        {
          "number": "13.1",
          "title": "Prelude to Equilibrium",
          "ready": true,
          "file": "genchem-1e/Fundamental-Equilibrium-Concepts/13-1-Prelude-to-Equilibrium.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/General_Chemistry/Chemistry_1e_(OpenSTAX)/13%3A_Fundamental_Equilibrium_Concepts/13.01%3A_Prelude_to_Equilibrium"
        },
        {
          "number": "13.2",
          "title": "Chemical Equilibria",
          "ready": true,
          "file": "genchem-1e/Fundamental-Equilibrium-Concepts/13-2-Chemical-Equilibria.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/General_Chemistry/Chemistry_1e_(OpenSTAX)/13%3A_Fundamental_Equilibrium_Concepts/13.02%3A_Chemical_Equilibria"
        },
        {
          "number": "13.3",
          "title": "Equilibrium Constants",
          "ready": true,
          "file": "genchem-1e/Fundamental-Equilibrium-Concepts/13-3-Equilibrium-Constants.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/General_Chemistry/Chemistry_1e_(OpenSTAX)/13%3A_Fundamental_Equilibrium_Concepts/13.03%3A_Equilibrium_Constants"
        },
        {
          "number": "13.4",
          "title": "Shifting Equilibria - Le Chatelier's Principle",
          "ready": true,
          "file": "genchem-1e/Fundamental-Equilibrium-Concepts/13-4-Shifting-Equilibria-Le-Chateliers-Principle.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/General_Chemistry/Chemistry_1e_(OpenSTAX)/13%3A_Fundamental_Equilibrium_Concepts/13.04%3A_Shifting_Equilibria_-_Le_Chateliers_Principle"
        },
        {
          "number": "13.5",
          "title": "Equilibrium Calculations",
          "ready": true,
          "file": "genchem-1e/Fundamental-Equilibrium-Concepts/13-5-Equilibrium-Calculations.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/General_Chemistry/Chemistry_1e_(OpenSTAX)/13%3A_Fundamental_Equilibrium_Concepts/13.05%3A_Equilibrium_Calculations"
        }
      ]
    },
    {
      "number": 14,
      "title": "Acid-Base Equilibria",
      "sections": [
        {
          "number": "14.1",
          "title": "Bronsted-Lowry Acids and Bases",
          "ready": true,
          "file": "genchem-1e/Acid-Base-Equilibria/14-1-Bronsted-Lowry-Acids-and-Bases.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/General_Chemistry/Chemistry_1e_(OpenSTAX)/14%3A_Acid-Base_Equilibria/14.01%3A_Brnsted-Lowry_Acids_and_Bases"
        },
        {
          "number": "14.2",
          "title": "pH and pOH",
          "ready": true,
          "file": "genchem-1e/Acid-Base-Equilibria/14-2-pH-and-pOH.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/General_Chemistry/Chemistry_1e_(OpenSTAX)/14%3A_Acid-Base_Equilibria/14.02%3A_pH_and_pOH"
        },
        {
          "number": "14.3",
          "title": "Relative Strengths of Acids and Bases",
          "ready": true,
          "file": "genchem-1e/Acid-Base-Equilibria/14-3-Relative-Strengths-of-Acids-and-Bases.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/General_Chemistry/Chemistry_1e_(OpenSTAX)/14%3A_Acid-Base_Equilibria/14.03%3A_Relative_Strengths_of_Acids_and_Bases"
        },
        {
          "number": "14.4",
          "title": "Hydrolysis of Salt Solutions",
          "ready": true,
          "file": "genchem-1e/Acid-Base-Equilibria/14-4-Hydrolysis-of-Salt-Solutions.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/General_Chemistry/Chemistry_1e_(OpenSTAX)/14%3A_Acid-Base_Equilibria/14.04%3A_Hydrolysis_of_Salt_Solutions"
        },
        {
          "number": "14.5",
          "title": "Polyprotic Acids",
          "ready": true,
          "file": "genchem-1e/Acid-Base-Equilibria/14-5-Polyprotic-Acids.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/General_Chemistry/Chemistry_1e_(OpenSTAX)/14%3A_Acid-Base_Equilibria/14.05%3A_Polyprotic_Acids"
        },
        {
          "number": "14.6",
          "title": "Buffers",
          "ready": true,
          "file": "genchem-1e/Acid-Base-Equilibria/14-6-Buffers.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/General_Chemistry/Chemistry_1e_(OpenSTAX)/14%3A_Acid-Base_Equilibria/14.06%3A_Buffers"
        },
        {
          "number": "14.7",
          "title": "Acid-Base Titrations",
          "ready": true,
          "file": "genchem-1e/Acid-Base-Equilibria/14-7-Acid-Base-Titrations.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/General_Chemistry/Chemistry_1e_(OpenSTAX)/14%3A_Acid-Base_Equilibria/14.07%3A_Acid-Base_Titrations"
        }
      ]
    },
    {
      "number": 15,
      "title": "Equilibria of Other Reaction Classes",
      "sections": [
        {
          "number": "15.1",
          "title": "Precipitation and Dissolution",
          "ready": true,
          "file": "genchem-1e/Equilibria-of-Other-Reaction-Classes/15-1-Precipitation-and-Dissolution.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/General_Chemistry/Chemistry_1e_(OpenSTAX)/15%3A_Equilibria_of_Other_Reaction_Classes/15.01%3A_Precipitation_and_Dissolution"
        },
        {
          "number": "15.2",
          "title": "Lewis Acids and Bases",
          "ready": true,
          "file": "genchem-1e/Equilibria-of-Other-Reaction-Classes/15-2-Lewis-Acids-and-Bases.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/General_Chemistry/Chemistry_1e_(OpenSTAX)/15%3A_Equilibria_of_Other_Reaction_Classes/15.02%3A_Lewis_Acids_and_Bases"
        },
        {
          "number": "15.3",
          "title": "Coupled Equilibria",
          "ready": true,
          "file": "genchem-1e/Equilibria-of-Other-Reaction-Classes/15-3-Coupled-Equilibria.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/General_Chemistry/Chemistry_1e_(OpenSTAX)/15%3A_Equilibria_of_Other_Reaction_Classes/15.03%3A_Coupled_Equilibria"
        }
      ]
    },
    {
      "number": 16,
      "title": "Thermodynamics",
      "sections": [
        {
          "number": "16.1",
          "title": "Spontaneity",
          "ready": true,
          "file": "genchem-1e/Thermodynamics/16-1-Spontaneity.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/General_Chemistry/Chemistry_1e_(OpenSTAX)/16%3A_Thermodynamics/16.01%3A_Spontaneity"
        },
        {
          "number": "16.2",
          "title": "Entropy",
          "ready": true,
          "file": "genchem-1e/Thermodynamics/16-2-Entropy.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/General_Chemistry/Chemistry_1e_(OpenSTAX)/16%3A_Thermodynamics/16.02%3A_Entropy"
        },
        {
          "number": "16.3",
          "title": "The Second and Third Laws of Thermodynamics",
          "ready": true,
          "file": "genchem-1e/Thermodynamics/16-3-The-Second-and-Third-Laws-of-Thermodynamics.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/General_Chemistry/Chemistry_1e_(OpenSTAX)/16%3A_Thermodynamics/16.03%3A_The_Second_and_Third_Laws_of_Thermodynamics"
        },
        {
          "number": "16.4",
          "title": "Gibbs Energy",
          "ready": true,
          "file": "genchem-1e/Thermodynamics/16-4-Gibbs-Energy.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/General_Chemistry/Chemistry_1e_(OpenSTAX)/16%3A_Thermodynamics/16.04%3A_Gibbs_Energy"
        }
      ]
    },
    {
      "number": 17,
      "title": "Electrochemistry",
      "sections": [
        {
          "number": "17.1",
          "title": "Balancing Oxidation-Reduction Reactions",
          "ready": true,
          "file": "genchem-1e/Electrochemistry/17-1-Balancing-Oxidation-Reduction-Reactions.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/General_Chemistry/Chemistry_1e_(OpenSTAX)/17%3A_Electrochemistry/17.01%3A_Balancing_Oxidation-Reduction_Reactions"
        },
        {
          "number": "17.2",
          "title": "Galvanic Cells",
          "ready": true,
          "file": "genchem-1e/Electrochemistry/17-2-Galvanic-Cells.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/General_Chemistry/Chemistry_1e_(OpenSTAX)/17%3A_Electrochemistry/17.02%3A_Galvanic_Cells"
        },
        {
          "number": "17.3",
          "title": "Standard Reduction Potentials",
          "ready": true,
          "file": "genchem-1e/Electrochemistry/17-3-Standard-Reduction-Potentials.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/General_Chemistry/Chemistry_1e_(OpenSTAX)/17%3A_Electrochemistry/17.03%3A_Standard_Reduction_Potentials"
        },
        {
          "number": "17.4",
          "title": "The Nernst Equation",
          "ready": true,
          "file": "genchem-1e/Electrochemistry/17-4-The-Nernst-Equation.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/General_Chemistry/Chemistry_1e_(OpenSTAX)/17%3A_Electrochemistry/17.04%3A_The_Nernst_Equation"
        },
        {
          "number": "17.5",
          "title": "Batteries and Fuel Cells",
          "ready": true,
          "file": "genchem-1e/Electrochemistry/17-5-Batteries-and-Fuel-Cells.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/General_Chemistry/Chemistry_1e_(OpenSTAX)/17%3A_Electrochemistry/17.05%3A_Batteries_and_Fuel_Cells"
        },
        {
          "number": "17.6",
          "title": "Corrosion",
          "ready": true,
          "file": "genchem-1e/Electrochemistry/17-6-Corrosion.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/General_Chemistry/Chemistry_1e_(OpenSTAX)/17%3A_Electrochemistry/17.06%3A_Corrosion"
        },
        {
          "number": "17.7",
          "title": "Electrolysis",
          "ready": true,
          "file": "genchem-1e/Electrochemistry/17-7-Electrolysis.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/General_Chemistry/Chemistry_1e_(OpenSTAX)/17%3A_Electrochemistry/17.07%3A_Electrolysis"
        }
      ]
    },
    {
      "number": 18,
      "title": "Representative Metals, Metalloids, and Nonmetals",
      "sections": [
        {
          "number": "18.1",
          "title": "Periodicity",
          "ready": true,
          "file": "genchem-1e/Representative-Metals-Metalloids-and-Nonmetals/18-1-Periodicity.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/General_Chemistry/Chemistry_1e_(OpenSTAX)/18%3A_Representative_Metals_Metalloids_and_Nonmetals/18.01%3A_Periodicity"
        },
        {
          "number": "18.2",
          "title": "Occurrence and Preparation of the Representative Metals",
          "ready": true,
          "file": "genchem-1e/Representative-Metals-Metalloids-and-Nonmetals/18-2-Occurrence-and-Preparation-of-the-Representative-Metals.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/General_Chemistry/Chemistry_1e_(OpenSTAX)/18%3A_Representative_Metals_Metalloids_and_Nonmetals/18.02%3A_Occurrence_and_Preparation_of_the_Representative_Metals"
        },
        {
          "number": "18.3",
          "title": "Structure and General Properties of the Metalloids",
          "ready": true,
          "file": "genchem-1e/Representative-Metals-Metalloids-and-Nonmetals/18-3-Structure-and-General-Properties-of-the-Metalloids.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/General_Chemistry/Chemistry_1e_(OpenSTAX)/18%3A_Representative_Metals_Metalloids_and_Nonmetals/18.03%3A_Structure_and_General_Properties_of_the_Metalloids"
        },
        {
          "number": "18.4",
          "title": "Structure and General Properties of the Nonmetals",
          "ready": true,
          "file": "genchem-1e/Representative-Metals-Metalloids-and-Nonmetals/18-4-Structure-and-General-Properties-of-the-Nonmetals.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/General_Chemistry/Chemistry_1e_(OpenSTAX)/18%3A_Representative_Metals_Metalloids_and_Nonmetals/18.04%3A_Structure_and_General_Properties_of_the_Nonmetals"
        },
        {
          "number": "18.5",
          "title": "Occurrence, Preparation, and Compounds of Hydrogen",
          "ready": true,
          "file": "genchem-1e/Representative-Metals-Metalloids-and-Nonmetals/18-5-Occurrence-Preparation-and-Compounds-of-Hydrogen.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/General_Chemistry/Chemistry_1e_(OpenSTAX)/18%3A_Representative_Metals_Metalloids_and_Nonmetals/18.05%3A_Occurrence_Preparation_and_Compounds_of_Hydrogen"
        },
        {
          "number": "18.6",
          "title": "Occurrence, Preparation, and Properties of Carbonates",
          "ready": true,
          "file": "genchem-1e/Representative-Metals-Metalloids-and-Nonmetals/18-6-Occurrence-Preparation-and-Properties-of-Carbonates.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/General_Chemistry/Chemistry_1e_(OpenSTAX)/18%3A_Representative_Metals_Metalloids_and_Nonmetals/18.06%3A_Occurrence_Preparation_and_Properties_of_Carbonates"
        },
        {
          "number": "18.7",
          "title": "Occurrence, Preparation, and Properties of Nitrogen",
          "ready": true,
          "file": "genchem-1e/Representative-Metals-Metalloids-and-Nonmetals/18-7-Occurrence-Preparation-and-Properties-of-Nitrogen.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/General_Chemistry/Chemistry_1e_(OpenSTAX)/18%3A_Representative_Metals_Metalloids_and_Nonmetals/18.07%3A_Occurrence_Preparation_and_Properties_of_Nitrogen"
        },
        {
          "number": "18.8",
          "title": "Occurrence, Preparation, and Properties of Phosphorus",
          "ready": true,
          "file": "genchem-1e/Representative-Metals-Metalloids-and-Nonmetals/18-8-Occurrence-Preparation-and-Properties-of-Phosphorus.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/General_Chemistry/Chemistry_1e_(OpenSTAX)/18%3A_Representative_Metals_Metalloids_and_Nonmetals/18.08%3A_Occurrence_Preparation_and_Properties_of_Phosphorus"
        },
        {
          "number": "18.9",
          "title": "Occurrence, Preparation, and Compounds of Oxygen",
          "ready": true,
          "file": "genchem-1e/Representative-Metals-Metalloids-and-Nonmetals/18-9-Occurrence-Preparation-and-Compounds-of-Oxygen.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/General_Chemistry/Chemistry_1e_(OpenSTAX)/18%3A_Representative_Metals_Metalloids_and_Nonmetals/18.09%3A_Occurrence_Preparation_and_Compounds_of_Oxygen"
        },
        {
          "number": "18.10",
          "title": "Occurrence, Preparation, and Properties of Sulfur",
          "ready": true,
          "file": "genchem-1e/Representative-Metals-Metalloids-and-Nonmetals/18-10-Occurrence-Preparation-and-Properties-of-Sulfur.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/General_Chemistry/Chemistry_1e_(OpenSTAX)/18%3A_Representative_Metals_Metalloids_and_Nonmetals/18.10%3A_Occurrence_Preparation_and_Properties_of_Sulfur"
        },
        {
          "number": "18.11",
          "title": "Occurrence, Preparation, and Properties of Halogens",
          "ready": true,
          "file": "genchem-1e/Representative-Metals-Metalloids-and-Nonmetals/18-11-Occurrence-Preparation-and-Properties-of-Halogens.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/General_Chemistry/Chemistry_1e_(OpenSTAX)/18%3A_Representative_Metals_Metalloids_and_Nonmetals/18.11%3A_Occurrence_Preparation_and_Properties_of_Halogens"
        },
        {
          "number": "18.12",
          "title": "Occurrence, Preparation, and Properties of the Noble Gases",
          "ready": true,
          "file": "genchem-1e/Representative-Metals-Metalloids-and-Nonmetals/18-12-Occurrence-Preparation-and-Properties-of-the-Noble-Gases.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/General_Chemistry/Chemistry_1e_(OpenSTAX)/18%3A_Representative_Metals_Metalloids_and_Nonmetals/18.12%3A_Occurrence_Preparation_and_Properties_of_the_Noble_Gases"
        }
      ]
    },
    {
      "number": 19,
      "title": "Transition Metals and Coordination Chemistry",
      "sections": [
        {
          "number": "19.1",
          "title": "Properties of Transition Metals and Their Compounds",
          "ready": true,
          "file": "genchem-1e/Transition-Metals-and-Coordination-Chemistry/19-1-Properties-of-Transition-Metals-and-Their-Compounds.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/General_Chemistry/Chemistry_1e_(OpenSTAX)/19%3A_Transition_Metals_and_Coordination_Chemistry/19.01%3A_Properties_of_Transition_Metals_and_Their_Compounds"
        },
        {
          "number": "19.2",
          "title": "Coordination Chemistry of Transition Metals",
          "ready": true,
          "file": "genchem-1e/Transition-Metals-and-Coordination-Chemistry/19-2-Coordination-Chemistry-of-Transition-Metals.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/General_Chemistry/Chemistry_1e_(OpenSTAX)/19%3A_Transition_Metals_and_Coordination_Chemistry/19.02%3A_Coordination_Chemistry_of_Transition_Metals"
        },
        {
          "number": "19.3",
          "title": "Optical and Magnetic Properties of Coordination Compounds",
          "ready": true,
          "file": "genchem-1e/Transition-Metals-and-Coordination-Chemistry/19-3-Optical-and-Magnetic-Properties-of-Coordination-Compounds.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/General_Chemistry/Chemistry_1e_(OpenSTAX)/19%3A_Transition_Metals_and_Coordination_Chemistry/19.03%3A_Optical_and_Magnetic_Properties_of_Coordination_Compounds"
        }
      ]
    },
    {
      "number": 20,
      "title": "Organic Chemistry",
      "sections": [
        {
          "number": "20.1",
          "title": "Prelude to Organic Chemistry",
          "ready": true,
          "file": "genchem-1e/Organic-Chemistry/20-1-Prelude-to-Organic-Chemistry.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/General_Chemistry/Chemistry_1e_(OpenSTAX)/20%3A_Organic_Chemistry/20.01%3A_Prelude_to_Organic_Chemistry"
        },
        {
          "number": "20.2",
          "title": "Hydrocarbons",
          "ready": true,
          "file": "genchem-1e/Organic-Chemistry/20-2-Hydrocarbons.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/General_Chemistry/Chemistry_1e_(OpenSTAX)/20%3A_Organic_Chemistry/20.02%3A_Hydrocarbons"
        },
        {
          "number": "20.3",
          "title": "Alcohols and Ethers",
          "ready": true,
          "file": "genchem-1e/Organic-Chemistry/20-3-Alcohols-and-Ethers.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/General_Chemistry/Chemistry_1e_(OpenSTAX)/20%3A_Organic_Chemistry/20.03%3A_Alcohols_and_Ethers"
        },
        {
          "number": "20.4",
          "title": "Aldehydes, Ketones, Carboxylic Acids, and Esters",
          "ready": true,
          "file": "genchem-1e/Organic-Chemistry/20-4-Aldehydes-Ketones-Carboxylic-Acids-and-Esters.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/General_Chemistry/Chemistry_1e_(OpenSTAX)/20%3A_Organic_Chemistry/20.04%3A_Aldehydes_Ketones_Carboxylic_Acids_and_Esters"
        },
        {
          "number": "20.5",
          "title": "Amines and Amides",
          "ready": true,
          "file": "genchem-1e/Organic-Chemistry/20-5-Amines-and-Amides.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/General_Chemistry/Chemistry_1e_(OpenSTAX)/20%3A_Organic_Chemistry/20.05%3A_Amines_and_Amides"
        }
      ]
    },
    {
      "number": 21,
      "title": "Nuclear Chemistry",
      "sections": [
        {
          "number": "21.1",
          "title": "Nuclear Structure and Stability",
          "ready": true,
          "file": "genchem-1e/Nuclear-Chemistry/21-1-Nuclear-Structure-and-Stability.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/General_Chemistry/Chemistry_1e_(OpenSTAX)/21%3A_Nuclear_Chemistry/21.01%3A_Nuclear_Structure_and_Stability"
        },
        {
          "number": "21.2",
          "title": "Nuclear Equations",
          "ready": true,
          "file": "genchem-1e/Nuclear-Chemistry/21-2-Nuclear-Equations.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/General_Chemistry/Chemistry_1e_(OpenSTAX)/21%3A_Nuclear_Chemistry/21.02%3A_Nuclear_Equations"
        },
        {
          "number": "21.3",
          "title": "Radioactive Decay",
          "ready": true,
          "file": "genchem-1e/Nuclear-Chemistry/21-3-Radioactive-Decay.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/General_Chemistry/Chemistry_1e_(OpenSTAX)/21%3A_Nuclear_Chemistry/21.03%3A_Radioactive_Decay"
        },
        {
          "number": "21.4",
          "title": "Transmutation and Nuclear Energy",
          "ready": true,
          "file": "genchem-1e/Nuclear-Chemistry/21-4-Transmutation-and-Nuclear-Energy.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/General_Chemistry/Chemistry_1e_(OpenSTAX)/21%3A_Nuclear_Chemistry/21.04%3A_Transmutation_and_Nuclear_Energy"
        },
        {
          "number": "21.5",
          "title": "Uses of Radioisotopes",
          "ready": true,
          "file": "genchem-1e/Nuclear-Chemistry/21-5-Uses-of-Radioisotopes.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/General_Chemistry/Chemistry_1e_(OpenSTAX)/21%3A_Nuclear_Chemistry/21.05%3A_Uses_of_Radioisotopes"
        },
        {
          "number": "21.6",
          "title": "Biological Effects of Radiation",
          "ready": true,
          "file": "genchem-1e/Nuclear-Chemistry/21-6-Biological-Effects-of-Radiation.md",
          "sourceUrl": "https://chem.libretexts.org/Bookshelves/General_Chemistry/Chemistry_1e_(OpenSTAX)/21%3A_Nuclear_Chemistry/21.06%3A_Biological_Effects_of_Radiation"
        }
      ]
    }
  ]
};

export const BOOK_META: Record<BookKey, BookMeta> = {
  "beginning-chemistry": {
    "title": "Beginning Chemistry (Ball)",
    "author": "Anonymous",
    "license": "CC BY-NC-SA 3.0"
  },
  "chemistry-1e": {
    "title": "Chemistry 1e (OpenStax)",
    "author": "OpenStax",
    "license": "CC BY 4.0"
  }
};
